### ISSUE TITLE
Unexpected error: Cannot read property 'isLooseListItem' of undefined

### ISSUE THREAD

**Issue by jiang3ye** [marktext/marktext#1055]
### Description

An unexpected error occurred in the main process.

### Stack Trace

```
TypeError: Cannot read property 'isLooseListItem' of undefined
    at isLooseListItem (C:\Program Files\Mark Text\resources\app.asar\dist\electron\webpack:\src\main\actions\paragraph.js:54:46)
    at Array.forEach (<anonymous>)
    at forEach (C:\Program Files\Mark Text\resources\app.asar\dist\electron\webpack:\src\main\actions\paragraph.js:48:35)
    at EventEmitter.setCheckedMenuItem (C:\Program Files\Mark Text\resources\app.asar\dist\electron\webpack:\src\main\actions\paragraph.js:98:3)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (C:\Program Files\Mark Text\resources\electron.asar\browser\api\web-contents.js:346:13)
    at WebContents.emit (events.js:182:13)
```

### Version

Mark Text: v0.14.0
Operating system: win32

**Comment by fxha** [comment]
Can you give us more information how to reproduce this issue?

**Comment by Jocs** [comment]
To be closed, feel free to reopen it if you have more info.
