### ISSUE TITLE
Unexpected error: Cannot read property 'nodeType' of null

### ISSUE THREAD

**Issue by iosmanthus** [marktext/marktext#1115]
### Description
When I try to select all pressing `Ctrl + a`, it reports: 
An unexpected error occurred in the renderer process.

### Stack Trace

```
TypeError: Cannot read property 'nodeType' of null
    at nodeType (file:///usr/share/marktext/app.asar/dist/electron/webpack:/src/muya/lib/selection/index.js:411:16)
    at A.getNodeAndOffset (file:///usr/share/marktext/app.asar/dist/electron/webpack:/src/muya/lib/selection/index.js:433:52)
    at A.setCursorRange (file:///usr/share/marktext/app.asar/dist/electron/webpack:/src/muya/lib/contentState/index.js:138:15)
    at A.setCursor (file:///usr/share/marktext/app.asar/dist/electron/webpack:/src/muya/lib/contentState/index.js:177:10)
    at A.partialRender [as backspaceHandler] (file:///usr/share/marktext/app.asar/dist/electron/webpack:/src/muya/lib/contentState/backspaceCtrl.js:355:12)
    at HTMLDivElement.backspaceHandler (file:///usr/share/marktext/app.asar/dist/electron/webpack:/src/muya/lib/eventHandler/keyboard.js:113:24)
```

### Version

Mark Text: v0.14.0 (af2098e)
Operating system: linux

**Comment by fxha** [comment]
@iosmanthus  Thank you for taking the time to report this issue. Based on the stack trace it's hard to reproduce this issue, could you please provide a minimal example or give more information how the exception occurred. There are also known issues with deleting and selecting the new image chooser that are not always reproducible.
