### ISSUE TITLE
Cannot extract heading when code block contains "# <text>"

### ISSUE THREAD

**Issue by yynps** [marktext/marktext#1128]
### Description

An unexpected error occurred in the main process.

### Stack Trace

```
TypeError: Cannot read property '1' of null
    at matches (E:\soft\mark text\resources\app.asar\dist\electron\webpack:\src\main\utils\index.js:31:14)
    at Array.map (<anonymous>)
    at map (E:\soft\mark text\resources\app.asar\dist\electron\webpack:\src\main\utils\index.js:28:24)
    at EventEmitter.getRecommendTitle (E:\soft\mark text\resources\app.asar\dist\electron\webpack:\src\main\actions\file.js:74:27)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (E:\soft\mark text\resources\electron.asar\browser\api\web-contents.js:346:13)
    at WebContents.emit (events.js:182:13)
```

### Version

Mark Text: v0.14.0
Operating system: win32

**Comment by fxha** [comment]
Thanks for taking the time to report this issue. Based on the stack trace it's hard to reproduce this issue, could you please provide a minimal example (e.g. markdown). It seems that there is an issue with parsing the markdown content to get the headings.

**Comment by fxha** [comment]
@Jocs I guess that this is an issue with our RegEx because we extract the heading text for the preferred filename from an code block like in #1150:

> I insert a code block and write some lines of python code. This error window first pops up when I type a "#" and it appears from time to time since then.

**Comment by Jocs** [comment]
@fxha Can you reproduce this bug now?

**Comment by fxha** [comment]
> Can you reproduce this bug now?

No, I can't reproduce this issue.
