### ISSUE TITLE
Electron 6 upgrade plan

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#1255]
- **Blocking:** Drop shadow flickering on Linux with Wayland ([upstream](https://github.com/electron/electron/issues/19699)).
- Verify features (there are many opened upstream issues about not working things).

**Breaking:**

- We need manually set `app.setAppLogsPath` to get Electron logs if needed.
- Use should use the new promise-based asynchronous dialog functions; Electron 5 dialog function have changed, maybe removed (?).

**Comment by fxha** [comment]
> @fxha I'am sorry, I forget to see this issue when I update Electron to 6 version, Do we still need this bellow:
> 
>     We need manually set app.setAppLogsPath to get Electron logs if needed.
> 
> I think we can roll back to Electron 5 when we publish new version if Electron does not solve there issues above?

I guess if this is not resolved before the next stable release. 

After you replaced `electron-rebuild` with `electron-builder install-app-deps` I cannot longer rebuild/build/launch Mark Text on Windows due an access denied error during `rebuild` and dependency installation phase. Do you have an idea why? I did not change anything on my system and also updated all components after this error occurred without success.

```
$ yarn
[...]
 $ electron-builder install-app-deps && npm run lint:fix
 Zugriff verweigert (access denied)
 verbose 1.251 Error: Command failed with exit code 1.
     at ProcessTermError.ExtendableBuiltin (<path>\yarn\lib\cli.js:721:66)
     at ProcessTermError.MessageError (<path>\yarn\lib\cli.js:750:123)
     at new ProcessTermError (<path>\yarn\lib\cli.js:790:113)
     at <path>\yarn\lib\cli.js:33879:30
     at Generator.throw (<anonymous>)
     at step (<path>\yarn\lib\cli.js:304:30)
     at <path>\yarn\lib\cli.js:317:13
     at process._tickCallback (internal/process/next_tick.js:68:7)
 error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by fxha** [comment]
Closing this because #655 has a higher priority than some GUI issue.
