### ISSUE TITLE
Delete unintended content when <> exists

### ISSUE THREAD

**Issue by EULIR** [marktext/marktext#1336]
### Description
When I have a passage like this
```
<><>
This is a paragraph.
This is another parapraph.
```
And I tried to delete content from the very beginning by pressing the delete key when the cursor is at the front. However, instead of deleting content word by word as intended, it deleted the first <> and the skip the first parapragh and started to delete the second paragraph.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. [First step]
Having a passage that includes at least three paragraphs which the first paragraph being ``<><>``
2. [Second step]
Move the cursor before the first ``<>``
3. [Third step]
Start pressing ``DELETE``

**Expected behavior:**
It first deletes ``<><>``, and then deletes the first paragraphs, and then deletes the second paragraphs. 

**Actual behavior:**
It deletes the first ``<>`` and then skips the first paragraph and deletes the second paragraphs. 

![img](https://s31.aconvert.com/convert/p3r68-cdx67/ckvi5-dmv8i.gif) 

### Versions

- Mark Text: 0.14.0
- Operating system: Windows 10.0.17134

**Comment by fxha** [comment]
@EULIR Thanks for reporting this issue.

**Stack Trace:**

```
Uncaught DOMException: Failed to execute 'setStart' on 'Range': The offset 4294967295 is larger than the node's length (2).
    at Object.setStart [as select] (file:///app/marktext/resources/app.asar/dist/electron/webpack:/src/muya/lib/selection/index.js:346:11)
    at Object.select [as setCursorRange] (file:///app/marktext/resources/app.asar/dist/electron/webpack:/src/muya/lib/selection/index.js:483:10)
    at Ps.setCursorRange [as setCursor] (file:///app/marktext/resources/app.asar/dist/electron/webpack:/src/muya/lib/contentState/index.js:159:15)
    at Ps.setCursor [as partialRender] (file:///app/marktext/resources/app.asar/dist/electron/webpack:/src/muya/lib/contentState/index.js:208:12)
    at Ps.partialRender [as inputHandler] (file:///app/marktext/resources/app.asar/dist/electron/webpack:/src/muya/lib/contentState/inputCtrl.js:261:51)
    at HTMLDivElement.inputHandler (file:///app/marktext/resources/app.asar/dist/electron/webpack:/src/muya/lib/eventHandler/keyboard.js:204:22)
```
