### ISSUE TITLE
Unexpected error: Cannot read property 'submenu' of null

### ISSUE THREAD

**Issue by mithenji** [marktext/marktext#1559]
### Description

An unexpected error occurred in the main process.

### Stack Trace

```
TypeError: Cannot read property 'submenu' of null
    at EventEmitter.<anonymous> (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:297438)
    at EventEmitter.emit (events.js:194:13)
    at WebContents.<anonymous> (/Applications/Mark Text.app/Contents/Resources/electron.asar/browser/api/web-contents.js:390:13)
    at WebContents.emit (events.js:194:13)
```

### Version

Mark Text: v0.15.0
Operating system: Darwin x64 19.0.0 (darwin)

**Comment by Jocs** [comment]
@mithenji How to reproduce this bug?

**Comment by Jocs** [comment]
We asked for more information to reproduce this issue but have not received a response. Closing due to inactivity — please reopen with reproduction steps if you can still reproduce this on the latest version.
