### ISSUE TITLE
Can not open folder by menu / open folder

### ISSUE THREAD

**Issue by Jocs** [marktext/marktext#1567]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Click open folder in `file` menu
2. The side bar is shown

**Expected behavior:**

The folder is opened, and I can see the markdown file in the folder in side bar.

**Actual behavior:**

<img width="911" alt="屏幕快照 2019-10-31 下午3 22 20" src="https://user-images.githubusercontent.com/9712830/67927054-93b0b680-fbf2-11e9-840b-a4d408c5929a.png">

**Link to an example: [optional]**

### Versions

- Mark Text: develop
- Operating system: all

**Comment by fxha** [comment]
@Jocs Works for me as expected with latest develop version.

**Comment by Jocs** [comment]
@fxha It's due to there are some asar file in my folder.

```sh
11:18:24.180 › Error while watching files: Error: Invalid package /Users/ransixi/Desktop/electron.asar
      at createError (electron/js2c/asar.js:124:17)
      at ReaddirpStream.fs.lstat (electron/js2c/asar.js:255:23)
      at internal/util.js:286:30
      at new Promise (<anonymous>)
      at ReaddirpStream._statMethod (internal/util.js:285:12)
      at ReaddirpStream._stat (/Users/ransixi/Documents/marktext/node_modules/readdirp/index.js:180:19)
      at ReaddirpStream._formatEntry (/Users/ransixi/Documents/marktext/node_modules/readdirp/index.js:193:28)
      at /Users/ransixi/Documents/marktext/node_modules/readdirp/index.js:153:64
      at Array.map (<anonymous>)
      at ReaddirpStream._exploreDirectory (/Users/ransixi/Documents/marktext/node_modules/readdirp/index.js:153:45)
```

**Comment by fxha** [comment]
@Jocs Could you please test again? I excluded `*.asar` from watcher due to this/a simular issue on Windows.

**Comment by Jocs** [comment]
@fxha it seems work well now.
