### ISSUE TITLE
Unexpected error: Failed to execute 'setStart' on 'Range': There is no child at offset 60.

### ISSUE THREAD

**Issue by CeroProgramming** [marktext/marktext#1715]
### Description

An unexpected error occurred in the renderer process.

I tried to mark LaTeX code with the cursor. The code was injected into markdown with $$

### Stack Trace

```
Error: Failed to execute 'setStart' on 'Range': There is no child at offset 60.
    at Object.select (file:///opt/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3266686)
    at Object.setCursorRange (file:///opt/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3268189)
    at Ps.setCursor (file:///opt/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3432934)
    at Ps.partialRender (file:///opt/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3433810)
    at Ps.Ss.A.clickHandler (file:///opt/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3422060)
    at HTMLDivElement.<anonymous> (file:///opt/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3456801)
```

### Version

Mark Text: v0.15.1 (a32c2c0)
Operating system: Linux x64 4.19.84-1-MANJARO (linux)

**Comment by fxha** [comment]
Thank @CeroProgramming  for taking the time to report this issue. We cannot reproduce the issue without steps to reproduce, please provide some steps like an example document.

**Comment by CeroProgramming** [comment]
I wasn't able to reproduce it at the moment, sorry :( . If it ever occurs again I will send you the code.

**Comment by CeroProgramming** [comment]
So, it happend again :O

Snippet:
```md
$\cap\,\mathfrak{U}$
```

Steps to reproduce:
Make sure the snippet is not selected (so you only see the rendered version) and try to mark the rendered equation with the cursor from the left to right with the cursor. It may not happen every time (I think it happend about two third of the time for me.

![GIF not loading?](https://i.ibb.co/VVB8jr4/Error-Mark-Text.gif)

Error:
```
An unexpected error occurred in the renderer process
Error: Failed to execute 'setStart' on 'Range': There is no child at offset 41.
    at Object.select (file:///opt/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3266686)
    at Object.setCursorRange (file:///opt/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3268189)
    at Ps.setCursor (file:///opt/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3432934)
    at Ps.partialRender (file:///opt/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3433810)
    at Ps.Ss.A.clickHandler (file:///opt/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3422060)
    at HTMLDivElement.<anonymous> (file:///opt/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3456801)
```

**Comment by Jocs** [comment]
Thanks for the (very patient) report from 2019. This crash is part of a long-standing `Range.setStart` offset family (later duplicates include #2526, #2627, #2800, #3378, …, #4159, #4321, #4338, #4353, #4367, #4372) where, after `partialRender`, the captured caret offset can exceed the new container's legal range — your `offset 60` while selecting a math formula falls into the same surface.

The defensive clamp landed on `develop` in #4358 (commit `1a2d2341`, 2026-06-04): `packages/muyajs/lib/selection/index.js` now bounds the offset by `childNodes.length` for element nodes and by text length for text nodes before forwarding to `Range.setStart` / `Range.setEnd` / `Selection.extend`. Your version (v0.15.1) very much predates the fix.

Closing as already fixed on `develop`. The fix will ship in the next release — please give it a try once it's out and feel free to reopen if you can still reproduce it there.
