### ISSUE TITLE
Unexpected error: Cannot read property 'submenu' of null

### ISSUE THREAD

**Issue by jzh9608** [marktext/marktext#1726]
### Description

An unexpected error occurred in the main process.

### Stack Trace

```
TypeError: Cannot read property 'submenu' of null
    at EventEmitter.<anonymous> (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:297468)
    at EventEmitter.emit (events.js:194:13)
    at WebContents.<anonymous> (/Applications/Mark Text.app/Contents/Resources/electron.asar/browser/api/web-contents.js:390:13)
    at WebContents.emit (events.js:194:13)
```

### Version

Mark Text: v0.15.1
Operating system: Darwin x64 18.7.0 (darwin)

**Comment by Jocs** [comment]
How to reproduce this issue?

**Comment by fxha** [comment]
Closing this issue as no further information has been provided. Please feel free to reopen with more information.
