### ISSUE TITLE
Headings containing shorthand emojis won't allow "Exporting to PDF / HTML"

### ISSUE THREAD

**Issue by naivros** [marktext/marktext#1738]
### Description

Using the shorthand emoji names (":angry&nbsp;:") within a header forces the application to refuse exporting silently; however, copying and pasting Unicode-8 emojis from an online repository (🙃) into the heading, allows exporting, as expected.

- [x] Can you reproduce the issue? 

### Steps to reproduce
**Note the \&nbsp character, to not render such shorthand names in this bug report.

1. Create new Note
2. Insert: :angry&nbsp;:
3. Ctrl+[1-6]: To make the line a heading.
4. File > Export > HTML or PDF

**Expected behavior:**

Successful exporting to a file, with a prompt requesting save location, or at least an error.

**Actual behavior:**

Nothing. Menu closes silently.

![unexpected](https://user-images.githubusercontent.com/28509720/69394894-2e506280-0c92-11ea-82fc-cff8f938961a.gif)

### Versions 
- Mark Text: v0.15.1
- Operating system: Windows 10 Pro

**Comment by fxha** [comment]
**Stack Trace:**

```
[error] Failed to export document: TypeError: this.renderer.emoji is not a function
Please report this to https://github.com/marktext/marktext/issues.
    at Lr.output (webpack:/src/muya/lib/parser/marked/inlineLexer.js:186:30)
    at Or.tok (webpack:/src/muya/lib/parser/marked/parser.js:95:34)
    at Or.parse (webpack:/src/muya/lib/parser/marked/parser.js:39:17)
    at marked (webpack:/src/muya/lib/parser/marked/index.js:22:28)
    at wa.renderHtml (webpack:/src/muya/lib/utils/exportHtml.js:108:16)
    at wa.generate (webpack:/src/muya/lib/utils/exportHtml.js:177:47)
    at cc.exportStyledHTML (webpack:/src/muya/lib/index.js:152:43)
    at s.apply (webpack:/src/renderer/components/editorWithTabs/editor.vue:949:1)
    at invokeWithErrorHandling (webpack:/node_modules/vue/dist/vue.esm.js:1863:26)
    at ft.A.$emit (webpack:/node_modules/vue/dist/vue.esm.js:3891:9)
```
