### ISSUE TITLE
Unexpected error: Cannot read property 'text' of null

### ISSUE THREAD

**Issue by idea-zone** [marktext/marktext#1741]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
TypeError: Cannot read property 'text' of null
    at Ps.A.checkNeedRender (file:///D:/soft/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3324853)
    at Ps.Ss.A.clickHandler (file:///D:/soft/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3425112)
    at HTMLDivElement.<anonymous> (file:///D:/soft/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3459967)
```

### Version

Mark Text: v0.15.0 (96f3f73)
Operating system: Windows_NT x64 10.0.18362 (win32)

**Comment by fxha** [comment]
Thank you for reporting the issue. We cannot reproduce this issue without steps to reproduce, please provide some steps or how the error occurred.

**Comment by idea-zone** [comment]
Occurrence status is the same as #1742. You can see in  https://github.com/marktext/marktext/issues/1742#issuecomment-560260583 .
