### ISSUE TITLE
Unexpected error: Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by idea-zone** [marktext/marktext#1742]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
TypeError: Cannot read property 'children' of undefined
    at ds.normalizeCodeBlock (file:///D:/soft/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3391188)
    at ds.translateBlocks2Markdown (file:///D:/soft/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3389950)
    at ds.generate (file:///D:/soft/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3388315)
    at rr.getMarkdown (file:///D:/soft/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3462805)
    at rr.Br.dispatchChange (file:///D:/soft/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3466536)
    at file:///D:/soft/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3454122
```

### Version

Mark Text: v0.15.0 (96f3f73)
Operating system: Windows_NT x64 10.0.18362 (win32)

**Comment by Rahuly2k** [comment]
I want to work on this issue

**Comment by fxha** [comment]
@Rahuly2k Sure, of course you can but we still need further information/steps to reproduce this issue.

**Comment by idea-zone** [comment]
Do you Know Evernote? I use its chinese vserion: yinxiangbiji . I add the *.md file to yinxiangbiji as an annex in one of note. I open the *.md file in yinxiangbiji and edit with marktext. Sometime marktext will be error.Here a image as instructions. My English is not good, I also give a Chinese response：
---
我用 Evenote 的中文版本：印象笔记。使用场景是：我把 md 文件作为附件添加道印象笔记的某个笔记中，然后在印象笔记中打开 md 文件，用 Marktext 软件编辑。有时 Marktext 会报错。附上一张图：
---
![image.png](https://i.loli.net/2019/12/02/wSdPqKfEynkHhZG.png)

**Comment by Jocs** [comment]
@idea-zone 将 markdown 文件放到其他文件夹，在右键打开也会出问题吗？

**Comment by Jocs** [comment]
Closing — this crash was reported against the legacy webpack-bundled build (the stack trace points into `dist/electron/renderer.js` / `dist/electron/main.js` / `webpack:/marktext/...`, which no longer exists).

The renderer + main process were rewritten on top of electron-vite in [PR #4001](https://github.com/marktext/marktext/pull/4001) (commit 85607dd2, shipped in 0.18.x). Many of the crash sites referenced in stacks like this were either rewritten, replaced, or now sit behind explicit guards. The general "Unexpected error" surface was also re-audited and given regression tests in [PR #4268](https://github.com/marktext/marktext/pull/4268).

**Please upgrade to the latest 0.18.x build. If you still hit a crash on a recent build, please reopen with the new MarkText version and the steps that triggered it — the new stack traces will point us to the actual current code.**
