### ISSUE TITLE
Unexpected error: Cannot destructure property 'row' of 'i' as it is null.

### ISSUE THREAD

**Issue by ximing** [marktext/marktext#1825]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
TypeError: Cannot destructure property 'row' of 'i' as it is null.
    at wa.Rr.A.deleteSelectedTableCells (file:///Applications/Mark%20Text.app/Contents/Resources/app.asar/dist/electron/renderer.js:70:2628301)
    at wa.A.docBackspaceHandler (file:///Applications/Mark%20Text.app/Contents/Resources/app.asar/dist/electron/renderer.js:70:2603745)
    at HTMLDocument.<anonymous> (file:///Applications/Mark%20Text.app/Contents/Resources/app.asar/dist/electron/renderer.js:70:2756694)
```

### Version

Mark Text: v0.16.0-rc.2 (270aaac)
Operating system: Darwin x64 19.0.0 (darwin)

**Comment by ximing** [comment]
This bug is easily reproduced steadily.
This is a screen-recorded gif.
![QQ20191216-213119](https://user-images.githubusercontent.com/4659887/70910811-75d8cd00-204b-11ea-94ca-512c3e004ce8.gif)
first insert a table, and select all cell.  delete it.
then input some character , then to delete character.  reproduced....
