### ISSUE TITLE
Unexpected error: Config schema violation: `spellcheckerLanguage` should match pattern "^[a-z]{2}(?:[-][A-Z]{2})?$"

### ISSUE THREAD

**Issue by ravish-tech** [marktext/marktext#1826]
### Description

An unexpected error occurred in the main process.

### Stack Trace

```
Error: Config schema violation: `spellcheckerLanguage` should match pattern "^[a-z]{2}(?:[-][A-Z]{2})?$"
    at ElectronStore._validate (C:\Users\rkumar323\AppData\Local\Programs\Mark Text\resources\app.asar\node_modules\conf\index.js:154:10)
    at ElectronStore.set store [as store] (C:\Users\rkumar323\AppData\Local\Programs\Mark Text\resources\app.asar\node_modules\conf\index.js:448:8)
    at ElectronStore.set (C:\Users\rkumar323\AppData\Local\Programs\Mark Text\resources\app.asar\node_modules\conf\index.js:327:14)
    at yn.setItem (C:\Users\rkumar323\AppData\Local\Programs\Mark Text\resources\app.asar\dist\electron\main.js:2:328216)
    at C:\Users\rkumar323\AppData\Local\Programs\Mark Text\resources\app.asar\dist\electron\main.js:2:328303
    at Array.map (<anonymous>)
    at yn.setItems (C:\Users\rkumar323\AppData\Local\Programs\Mark Text\resources\app.asar\dist\electron\main.js:2:328290)
    at IpcMain.<anonymous> (C:\Users\rkumar323\AppData\Local\Programs\Mark Text\resources\app.asar\dist\electron\main.js:2:328745)
    at IpcMain.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3768:15)
```

### Version

Mark Text: v0.16.0-rc.2
Operating system: Windows_NT x64 10.0.18362 (win32)

**Comment by fxha** [comment]
Thanks for reporting the issue. Could you please open the [application data directory](https://github.com/marktext/marktext/blob/develop/docs/APPLICATION_DATA_DIRECTORY.md) and post the line containing `"spellcheckerLanguage"` in `preferences.json`. It should be something like `"spellcheckerLanguage": "de-DE",` and you could set the value `"de-DE"` to `"en-US"` to workaround the validation.

**Comment by ravish-tech** [comment]
It is set as below. but I should mention after above error, I just installed the "v0.16.0-rc.2" version and have been happy about it.
"spellcheckerLanguage": "en-US",
Happy for this to be closed. As you description above should help someone if they do get this.
