### ISSUE TITLE
Unexpected error: Cannot read property 'text' of null

### ISSUE THREAD

**Issue by pihentagy** [marktext/marktext#1853]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
TypeError: Cannot read property 'text' of null
    at Ea.checkNeedRender (file:///tmp/.mount_markteFQJhGC/resources/app.asar/dist/electron/webpack:/src/muya/lib/contentState/updateCtrl.js:42:46)
    at Ea.inputHandler (file:///tmp/.mount_markteFQJhGC/resources/app.asar/dist/electron/webpack:/src/muya/lib/contentState/inputCtrl.js:309:102)
    at HTMLDivElement.<anonymous> (file:///tmp/.mount_markteFQJhGC/resources/app.asar/dist/electron/webpack:/src/muya/lib/eventHandler/keyboard.js:203:22)
```

### Version

Mark Text: v0.16.0-rc.2 (593ca5f)
Operating system: Linux x64 5.0.0-37-generic (linux)

**Comment by gus3000** [comment]
I have a very similar issue (I think):
### Stack Trace (1st pop-up)

```
TypeError: Cannot destructure property `text` of 'undefined' or 'null'.
    at Ps.Fs.A.updateParagraph (file:///opt/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3400663)
    at dB.selectItem (file:///opt/Mark%20Text/resources/app.asar/dist/electron/renderer.js:44:29893)
    at HTMLDivElement.<anonymous> (file:///opt/Mark%20Text/resources/app.asar/dist/electron/renderer.js:44:25132)
```

### Stack trace (2nd popup)
```
An unexpected error occurred in the renderer process
TypeError: Cannot read property 'text' of null
    at Ps.A.checkNeedRender (file:///opt/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3321694)
    at HTMLDivElement.<anonymous> (file:///opt/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3453396)
```

### When does this happen ?
When I use @ to insert a code block. Note : the code block seems correctly inserted afterwards, and is usable. However, every time I click in it, the pop-ups reappear.
This does not seem to happen for other kind of blocks.

**Comment by Jocs** [comment]
@pihentagy How to reproduce this problem?

**Comment by pihentagy** [comment]
> @pihentagy How to reproduce this problem?

Sorry for making noise. This bug was invalid, I tampered the code (tried to implement separating recent files and folders).
