### ISSUE TITLE
Unexpected error: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by pihentagy** [marktext/marktext#1867]
### Description

An unexpected error occurred in the main process.

### Stack Trace

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.resolve (path.js:981:7)
    at ue (/opt/Mark Text/resources/app.asar/dist/electron/main.js:2:258636)
    at _t (/opt/Mark Text/resources/app.asar/dist/electron/main.js:2:288961)
    at Lt (/opt/Mark Text/resources/app.asar/dist/electron/main.js:2:301012)
    at Dt._buildEditorMenu (/opt/Mark Text/resources/app.asar/dist/electron/main.js:2:286224)
    at Dt.addEditorMenu (/opt/Mark Text/resources/app.asar/dist/electron/main.js:2:284706)
    at Kt.createWindow (/opt/Mark Text/resources/app.asar/dist/electron/main.js:2:304233)
    at Zt._createEditorWindow (/opt/Mark Text/resources/app.asar/dist/electron/main.js:2:313473)
    at App.<anonymous> (/opt/Mark Text/resources/app.asar/dist/electron/main.js:2:311748)
```

### Version

Mark Text: v0.16.0-rc.2 (593ca5f)
Operating system: Linux x64 5.0.0-37-generic (linux)

**Comment by pihentagy** [comment]
Invalid bug, sorry
