### ISSUE TITLE
Unexpected error: Cannot read property 'getMenuItemById' of null

### ISSUE THREAD

**Issue by RoderickQiu** [marktext/marktext#1887]
### Description

An unexpected error occurred in the main process.

After I started settings, an error is directly shown.

### Stack Trace

```
TypeError: Cannot read property 'getMenuItemById' of null
    at Gt (C:\Program Files\Mark Text\resources\app.asar\dist\electron\main.js:2:305423)
    at EventEmitter.<anonymous> (C:\Program Files\Mark Text\resources\app.asar\dist\electron\main.js:2:297737)
    at EventEmitter.emit (events.js:194:13)
    at WebContents.<anonymous> (C:\Program Files\Mark Text\resources\electron.asar\browser\api\web-contents.js:390:13)
    at WebContents.emit (events.js:194:13)
```

### Version

Mark Text: v0.15.1
Operating system: Windows_NT x64 10.0.18363 (win32)

**Comment by Jocs** [comment]
Can you always reproduce this issue?

**Comment by RoderickQiu** [comment]
Increadibly, I cannot reproduce this issue currently... But still, if you've got time, you can check that 'getMenuItemById', still v0.15.1.
