### ISSUE TITLE
在 Manjaro Linux 上通过 AUR 安装失败

### ISSUE THREAD

**Issue by blleng** [marktext/marktext#1984]
### Description

我尝试在 Manjaro 上通过AUR安装Marktext，但是失败了。

失败出现在 prepate() 中，执行 `electron-rebuild -f` 时发生了错误：

```bash
[4/4] Building fresh packages...
$ yarn run rebuild && yarn run lint:fix
yarn run v1.22.0
$ electron-rebuild -f
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@13.10.1 | linux | x64
gyp info find Python using Python version 3.8.1 found at "/usr/bin/python3"
gyp http GET https://electronjs.org/headers/v8.0.1/node-v8.0.1-headers.tar.gz
gyp http 200 https://electronjs.org/headers/v8.0.1/node-v8.0.1-headers.tar.gz
gyp http GET https://electronjs.org/headers/v8.0.1/SHASUMS256.txt
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: connect ETIMEDOUT 52.216.179.187:443
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
gyp ERR! System Linux 5.5.8-1-MANJARO
gyp ERR! command "/usr/bin/node" "/home/leng/.cache/yay/marktext-git/src/marktext/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=8.0.1" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /home/leng/.cache/yay/marktext-git/src/marktext/node_modules/cld
gyp ERR! node -v v13.10.1
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@13.10.1 | linux | x64
gyp info find Python using Python version 3.8.1 found at "/usr/bin/python3"
gyp http GET https://electronjs.org/headers/v8.0.1/node-v8.0.1-headers.tar.gz
gyp http 200 https://electronjs.org/headers/v8.0.1/node-v8.0.1-headers.tar.gz
gyp http GET https://electronjs.org/headers/v8.0.1/SHASUMS256.txt
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: connect ETIMEDOUT 52.216.179.187:443
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
gyp ERR! System Linux 5.5.8-1-MANJARO
gyp ERR! command "/usr/bin/node" "/home/leng/.cache/yay/marktext-git/src/marktext/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=8.0.1" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /home/leng/.cache/yay/marktext-git/src/marktext/node_modules/cld
gyp ERR! node -v v13.10.1
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (/home/leng/.cache/yay/marktext-git/src/marktext/node_modules/spawn-rx/lib/src/index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (/home/leng/.cache/yay/marktext-git/src/marktext/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.error (/home/leng/.cache/yay/marktext-git/src/marktext/node_modules/rxjs/internal/Subscriber.js:156:26)
    at Subscriber._error (/home/leng/.cache/yay/marktext-git/src/marktext/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/home/leng/.cache/yay/marktext-git/src/marktext/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/home/leng/.cache/yay/marktext-git/src/marktext/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/home/leng/.cache/yay/marktext-git/src/marktext/node_modules/rxjs/internal/Subscriber.js:72:18)
    at SafeSubscriber._next (/home/leng/.cache/yay/marktext-git/src/marktext/node_modules/spawn-rx/lib/src/index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (/home/leng/.cache/yay/marktext-git/src/marktext/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/home/leng/.cache/yay/marktext-git/src/marktext/node_modules/rxjs/internal/Subscriber.js:143:22)
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
==> 错误： 在 prepare() 中发生一个错误。
    正在放弃...
Error making: marktext-git
```

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. `yay -S marktext-git`
2. All packages to CleanBuild
3. None diffs to show
4. Fail

**Expected behavior:**
成功安装

**Actual behavior:**
安装失败

**Link to an example: [optional]**

### Versions

- Mark Text: marktext-git-r1380.65f1bef3-1
- Operating system: Linux 5.5.8-1-MANJARO

**Comment by fxha** [comment]
Thank you for taking the time to report this issue. Based on the provided data, we'll go ahead and close this issue as it's not an official packages; only a community maintained package.

**Comment by blleng** [comment]
Ok, thanks for your reply.
