### ISSUE TITLE
yarn install error

### ISSUE THREAD

**Issue by MrHeer** [marktext/marktext#2003]
### Question description
When I run `yarn install`, will appear the following error. Is there any way to solve it？
```bash
yarn install v1.21.1
$ node .electron-vue/preinstall.js
[1/4] Resolving packages...
warning element-ui > async-validator > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning popper.js@1.16.1: Popper changed home, find its new releases at @popperjs/core
warning karma-coverage > istanbul@0.4.5: This module is no longer maintained, try this instead:
  npm i nyc
Visit https://istanbul.js.org/integrations for other alternatives.
warning mocha > mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning spectron > webdriverio@4.14.4: outdated version, please use @next
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/14] ⠈ @hfelix/spellchecker
[2/14] ⠈ cld
[8/14] ⠈ vscode-ripgrep
[4/14] ⠁ ced
error /home/mrheer/Documents/Src/Web/marktext/node_modules/vscode-ripgrep: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments: 
Directory: /home/mrheer/Documents/Src/Web/marktext/node_modules/vscode-ripgrep
Output:
Finding release for v11.0.1-2
GET https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v11.0.1-2
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 13.250.168.23:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
```

**Comment by Jocs** [comment]
Is it due to bad net connection?

**Comment by MrHeer** [comment]
Maybe, my network is accessible, but it seems that there is a problem accessing this resource.

**Comment by Jocs** [comment]
>Maybe, my network is accessible, but it seems that there is a problem accessing this resource.

Maybe, you need try again. Closed due to it's not an issue of Mark Text.
