### ISSUE TITLE
Unexpected error: callback can only be called for once

### ISSUE THREAD

**Issue by lorenzofanchi** [marktext/marktext#2060]
### Description

An unexpected error occurred in the main process.

Starting Mark Text after a fresh reboot. No special steps taken. Quitting and reopening the app mitigated the error.

### Stack Trace

```
TypeError: callback can only be called for once
    at Object.module.<computed> [as getAllDisplays] (electron/js2c/browser_init.js:6950:30)
    at ensureWindowVisibleOnSomeDisplay (/Applications/Mark Text.app/Contents/Resources/app.asar/node_modules/electron-window-state/index.js:58:28)
    at validateState (/Applications/Mark Text.app/Contents/Resources/app.asar/node_modules/electron-window-state/index.js:77:7)
    at module.exports (/Applications/Mark Text.app/Contents/Resources/app.asar/node_modules/electron-window-state/index.js:165:3)
    at Ut.createWindow (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:304276)
    at jt._createEditorWindow (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:315178)
    at jt.ready (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:313119)
    at App.<anonymous> (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:314274)
    at App.emit (events.js:210:5)
```

### Version

Mark Text: v0.16.1
Operating system: Darwin x64 19.4.0 (darwin)

**Comment by fxha** [comment]
Thank you for reporting the issue. I'm closing this because it's an upstream issue.
