### ISSUE TITLE
Unexpected error: callback can only be called for once

### ISSUE THREAD

**Issue by tudk** [marktext/marktext#2203]
### Description

An unexpected error occurred in the main process.

### Stack Trace

```
TypeError: callback can only be called for once
    at Object.module.<computed> [as getPrimaryDisplay] (electron/js2c/browser_init.js:6950:30)
    at /Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:304384
    at Ut.createWindow (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:304768)
    at jt._createEditorWindow (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:315178)
    at jt.ready (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:313119)
    at App.<anonymous> (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:314274)
    at App.emit (events.js:210:5)
```

### Version

Mark Text: v0.16.1
Operating system: Darwin x64 18.7.0 (darwin)

**Comment by Jocs** [comment]
Closing — this crash was reported against the legacy webpack-bundled build (the stack trace points into `dist/electron/renderer.js` / `dist/electron/main.js` / `webpack:/marktext/...`, which no longer exists).

The renderer + main process were rewritten on top of electron-vite in [PR #4001](https://github.com/marktext/marktext/pull/4001) (commit 85607dd2, shipped in 0.18.x). Many of the crash sites referenced in stacks like this were either rewritten, replaced, or now sit behind explicit guards. The general "Unexpected error" surface was also re-audited and given regression tests in [PR #4268](https://github.com/marktext/marktext/pull/4268).

**Please upgrade to the latest 0.18.x build. If you still hit a crash on a recent build, please reopen with the new MarkText version and the steps that triggered it — the new stack traces will point us to the actual current code.**
