### ISSUE TITLE
An unhandled error occurred inside electron-rebuild

### ISSUE THREAD

**Issue by Sandural** [marktext/marktext#2226]
### Description
>> yarn install
An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@14.4.0 | darwin | x64
gyp info find Python using Python version 3.7.7 found at "/usr/local/opt/python/bin/python3.7"
gyp http GET https://www.electronjs.org/headers/v8.3.1/node-v8.3.1-headers.tar.gz
gyp http 200 https://www.electronjs.org/headers/v8.3.1/node-v8.3.1-headers.tar.gz
gyp http GET https://www.electronjs.org/headers/v8.3.1/SHASUMS256.txt
gyp http 200 https://www.electronjs.org/headers/v8.3.1/SHASUMS256.txt
gyp info spawn /usr/local/opt/python/bin/python3.7
gyp info spawn args [
gyp info spawn args   '/Users/lizishan/Documents/Project/marktext/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/lizishan/Documents/Project/marktext/node_modules/watchpack-chokidar2/node_modules/fsevents/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/lizishan/Documents/Project/marktext/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/lizishan/.electron-gyp/8.3.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/lizishan/.electron-gyp/8.3.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/lizishan/Documents/Project/marktext/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/lizishan/.electron-gyp/8.3.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/lizishan/Documents/Project/marktext/node_modules/watchpack-chokidar2/node_modules/fsevents',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:56:
In file included from /Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:63:
/Users/lizishan/.electron-gyp/8.3.1/include/node/v8.h:4406:3: error: unterminated /* comment
  /**
  ^
/Users/lizishan/.electron-gyp/8.3.1/include/node/v8.h:15:2: error: unterminated conditional directive
#ifndef INCLUDE_V8_H_
 ^
/Users/lizishan/.electron-gyp/8.3.1/include/node/v8.h:4370:17: error: missing '}' at end of definition of 'v8::Function'
class V8_EXPORT Function : public Object {
                ^
/Users/lizishan/.electron-gyp/8.3.1/include/node/v8-platform.h:16:1: note: still within definition of 'v8::Function' here
namespace v8 {
^
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:56:
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:116:13: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
NODE_EXTERN v8::Local<v8::Value> ErrnoException(v8::Isolate* isolate,
            ^~~~~~~~~
            Local
/Users/lizishan/.electron-gyp/8.3.1/include/node/v8.h:189:7: note: 'Local' declared here
class Local {
      ^
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:56:
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:116:27: error: no member named 'Value' in namespace 'v8::v8'
NODE_EXTERN v8::Local<v8::Value> ErrnoException(v8::Isolate* isolate,
                      ~~~~^
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:121:13: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
NODE_EXTERN v8::Local<v8::Value> UVException(v8::Isolate* isolate,
            ^~~~~~~~~
            Local
/Users/lizishan/.electron-gyp/8.3.1/include/node/v8.h:189:7: note: 'Local' declared here
class Local {
      ^
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:56:
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:121:27: error: no member named 'Value' in namespace 'v8::v8'
NODE_EXTERN v8::Local<v8::Value> UVException(v8::Isolate* isolate,
                      ~~~~^
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:129:24: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
                inline v8::Local<v8::Value> ErrnoException(
                       ^~~~~~~~~
                       Local
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/lizishan/.electron-gyp/8.3.1/include/node/v8.h:189:7: note: 'Local' declared here
class Local {
      ^
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:56:
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:129:38: error: no member named 'Value' in namespace 'v8::v8'
                inline v8::Local<v8::Value> ErrnoException(
                                 ~~~~^
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:134:29: error: incomplete type 'v8::v8::Isolate' named in nested name specifier
  return ErrnoException(v8::Isolate::GetCurrent(),
                        ~~~~^~~~~~~~~
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/lizishan/.electron-gyp/8.3.1/include/node/v8-platform.h:18:7: note: forward declaration of 'v8::v8::Isolate'
class Isolate;
      ^
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:56:
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:142:24: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
                inline v8::Local<v8::Value> UVException(int errorno,
                       ^~~~~~~~~
                       Local
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/lizishan/.electron-gyp/8.3.1/include/node/v8.h:189:7: note: 'Local' declared here
class Local {
      ^
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:56:
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:142:38: error: no member named 'Value' in namespace 'v8::v8'
                inline v8::Local<v8::Value> UVException(int errorno,
                                 ~~~~^
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:146:26: error: incomplete type 'v8::v8::Isolate' named in nested name specifier
  return UVException(v8::Isolate::GetCurrent(),
                     ~~~~^~~~~~~~~
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/lizishan/.electron-gyp/8.3.1/include/node/v8-platform.h:18:7: note: forward declaration of 'v8::v8::Isolate'
class Isolate;
      ^
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:56:
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:161:29: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
                NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                            ^~~~~~~~~
                            Local
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/lizishan/.electron-gyp/8.3.1/include/node/v8.h:189:7: note: 'Local' declared here
class Local {
      ^
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:56:
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:161:43: error: no member named 'Value' in namespace 'v8::v8'
                NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                      ~~~~^
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:163:21: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
                    v8::Local<v8::Object> recv,
                    ^~~~~~~~~
                    Local
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/lizishan/.electron-gyp/8.3.1/include/node/v8.h:189:7: note: 'Local' declared here
class Local {
      ^
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:56:
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:163:35: error: no member named 'Object' in namespace 'v8::v8'
                    v8::Local<v8::Object> recv,
                              ~~~~^
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:166:21: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
                    v8::Local<v8::Value>* argv));
                    ^~~~~~~~~
                    Local
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/lizishan/.electron-gyp/8.3.1/include/node/v8.h:189:7: note: 'Local' declared here
class Local {
      ^
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:56:
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:166:35: error: no member named 'Value' in namespace 'v8::v8'
                    v8::Local<v8::Value>* argv));
                              ~~~~^
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/lizishan/Documents/Project/marktext/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/usr/local/Cellar/node/14.4.0/bin/node" "/Users/lizishan/Documents/Project/marktext/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=8.3.1" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /Users/lizishan/Documents/Project/marktext/node_modules/watchpack-chokidar2/node_modules/fsevents
gyp ERR! node -v v14.4.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@14.4.0 | darwin | x64
gyp info find Python using Python version 3.7.7 found at "/usr/local/opt/python/bin/python3.7"
gyp http GET https://www.electronjs.org/headers/v8.3.1/node-v8.3.1-headers.tar.gz
gyp http 200 https://www.electronjs.org/headers/v8.3.1/node-v8.3.1-headers.tar.gz
gyp http GET https://www.electronjs.org/headers/v8.3.1/SHASUMS256.txt
gyp http 200 https://www.electronjs.org/headers/v8.3.1/SHASUMS256.txt
gyp info spawn /usr/local/opt/python/bin/python3.7
gyp info spawn args [
gyp info spawn args   '/Users/lizishan/Documents/Project/marktext/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/lizishan/Documents/Project/marktext/node_modules/watchpack-chokidar2/node_modules/fsevents/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/lizishan/Documents/Project/marktext/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/lizishan/.electron-gyp/8.3.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/lizishan/.electron-gyp/8.3.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/lizishan/Documents/Project/marktext/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/lizishan/.electron-gyp/8.3.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/lizishan/Documents/Project/marktext/node_modules/watchpack-chokidar2/node_modules/fsevents',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:56:
In file included from /Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:63:
/Users/lizishan/.electron-gyp/8.3.1/include/node/v8.h:4406:3: error: unterminated /* comment
  /**
  ^
/Users/lizishan/.electron-gyp/8.3.1/include/node/v8.h:15:2: error: unterminated conditional directive
#ifndef INCLUDE_V8_H_
 ^
/Users/lizishan/.electron-gyp/8.3.1/include/node/v8.h:4370:17: error: missing '}' at end of definition of 'v8::Function'
class V8_EXPORT Function : public Object {
                ^
/Users/lizishan/.electron-gyp/8.3.1/include/node/v8-platform.h:16:1: note: still within definition of 'v8::Function' here
namespace v8 {
^
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:56:
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:116:13: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
NODE_EXTERN v8::Local<v8::Value> ErrnoException(v8::Isolate* isolate,
            ^~~~~~~~~
            Local
/Users/lizishan/.electron-gyp/8.3.1/include/node/v8.h:189:7: note: 'Local' declared here
class Local {
      ^
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:56:
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:116:27: error: no member named 'Value' in namespace 'v8::v8'
NODE_EXTERN v8::Local<v8::Value> ErrnoException(v8::Isolate* isolate,
                      ~~~~^
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:121:13: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
NODE_EXTERN v8::Local<v8::Value> UVException(v8::Isolate* isolate,
            ^~~~~~~~~
            Local
/Users/lizishan/.electron-gyp/8.3.1/include/node/v8.h:189:7: note: 'Local' declared here
class Local {
      ^
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:56:
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:121:27: error: no member named 'Value' in namespace 'v8::v8'
NODE_EXTERN v8::Local<v8::Value> UVException(v8::Isolate* isolate,
                      ~~~~^
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:129:24: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
                inline v8::Local<v8::Value> ErrnoException(
                       ^~~~~~~~~
                       Local
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/lizishan/.electron-gyp/8.3.1/include/node/v8.h:189:7: note: 'Local' declared here
class Local {
      ^
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:56:
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:129:38: error: no member named 'Value' in namespace 'v8::v8'
                inline v8::Local<v8::Value> ErrnoException(
                                 ~~~~^
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:134:29: error: incomplete type 'v8::v8::Isolate' named in nested name specifier
  return ErrnoException(v8::Isolate::GetCurrent(),
                        ~~~~^~~~~~~~~
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/lizishan/.electron-gyp/8.3.1/include/node/v8-platform.h:18:7: note: forward declaration of 'v8::v8::Isolate'
class Isolate;
      ^
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:56:
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:142:24: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
                inline v8::Local<v8::Value> UVException(int errorno,
                       ^~~~~~~~~
                       Local
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/lizishan/.electron-gyp/8.3.1/include/node/v8.h:189:7: note: 'Local' declared here
class Local {
      ^
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:56:
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:142:38: error: no member named 'Value' in namespace 'v8::v8'
                inline v8::Local<v8::Value> UVException(int errorno,
                                 ~~~~^
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:146:26: error: incomplete type 'v8::v8::Isolate' named in nested name specifier
  return UVException(v8::Isolate::GetCurrent(),
                     ~~~~^~~~~~~~~
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/lizishan/.electron-gyp/8.3.1/include/node/v8-platform.h:18:7: note: forward declaration of 'v8::v8::Isolate'
class Isolate;
      ^
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:56:
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:161:29: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
                NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                            ^~~~~~~~~
                            Local
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/lizishan/.electron-gyp/8.3.1/include/node/v8.h:189:7: note: 'Local' declared here
class Local {
      ^
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:56:
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:161:43: error: no member named 'Value' in namespace 'v8::v8'
                NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                      ~~~~^
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:163:21: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
                    v8::Local<v8::Object> recv,
                    ^~~~~~~~~
                    Local
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/lizishan/.electron-gyp/8.3.1/include/node/v8.h:189:7: note: 'Local' declared here
class Local {
      ^
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:56:
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:163:35: error: no member named 'Object' in namespace 'v8::v8'
                    v8::Local<v8::Object> recv,
                              ~~~~^
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:166:21: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
                    v8::Local<v8::Value>* argv));
                    ^~~~~~~~~
                    Local
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/lizishan/.electron-gyp/8.3.1/include/node/v8.h:189:7: note: 'Local' declared here
class Local {
      ^
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:56:
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:166:35: error: no member named 'Value' in namespace 'v8::v8'
                    v8::Local<v8::Value>* argv));
                              ~~~~^
/Users/lizishan/.electron-gyp/8.3.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/lizishan/Documents/Project/marktext/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/usr/local/Cellar/node/14.4.0/bin/node" "/Users/lizishan/Documents/Project/marktext/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=8.3.1" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /Users/lizishan/Documents/Project/marktext/node_modules/watchpack-chokidar2/node_modules/fsevents
gyp ERR! node -v v14.4.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (/Users/lizishan/Documents/Project/marktext/node_modules/spawn-rx/lib/src/index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (/Users/lizishan/Documents/Project/marktext/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.error (/Users/lizishan/Documents/Project/marktext/node_modules/rxjs/internal/Subscriber.js:156:26)
    at Subscriber._error (/Users/lizishan/Documents/Project/marktext/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/Users/lizishan/Documents/Project/marktext/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/Users/lizishan/Documents/Project/marktext/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/Users/lizishan/Documents/Project/marktext/node_modules/rxjs/internal/Subscriber.js:72:18)
    at SafeSubscriber._next (/Users/lizishan/Documents/Project/marktext/node_modules/spawn-rx/lib/src/index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (/Users/lizishan/Documents/Project/marktext/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/Users/lizishan/Documents/Project/marktext/node_modules/rxjs/internal/Subscriber.js:143:22)
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 255.

### Versions

- Mark Text version:  lastest
- Operating system: 10.15.4 (19E287)

**Comment by Jocs** [comment]
Please try the latest develop branch.

**Comment by Jocs** [comment]
This error occurred with Node.js v14 and yarn, both of which are no longer supported. The project now requires **Node.js ≥20.19.0** and **pnpm@10.33.4**:
```bash
pnpm install
pnpm run dev
```
Closing as outdated environment.
