### ISSUE TITLE
travis-ci.org mac tests broken

### ISSUE THREAD

**Issue by brainchild0** [marktext/marktext#2254]
```
error /Users/travis/build/marktext/marktext/node_modules/vscode-ripgrep: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments: 
Directory: /Users/travis/build/marktext/marktext/node_modules/vscode-ripgrep
Output:
Finding release for v11.0.1-4
GET https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v11.0.1-4
Deleting invalid download cache
Downloading ripgrep failed: Error: Request failed: 403
    at ClientRequest.<anonymous> (/Users/travis/build/marktext/marktext/node_modules/vscode-ripgrep/lib/download.js:127:24)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:469:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command "yarn install --check-files --frozen-lockfile" failed and exited with 1 during .

Your build has been stopped.
```

---

See:
  - https://travis-ci.org/github/marktext/marktext/jobs/700318579
  - https://travis-ci.org/github/marktext/marktext/jobs/700491202

**Comment by Jocs** [comment]
We have removed `travis-ci`, so close this issue now.
