### ISSUE TITLE
Unexpected error: Cannot find window menu for id 1.

### ISSUE THREAD

**Issue by reven404** [marktext/marktext#2262]
### Description

An unexpected error occurred in the main process.

### Stack Trace

```
Error: Cannot find window menu for id 1.
    at ft.getWindowMenuById (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:250602)
    at IpcMainImpl.<anonymous> (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:252725)
    at IpcMainImpl.emit (events.js:210:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3908:15)
    at WebContents.emit (events.js:210:5)
```

### Version

Mark Text: v0.16.2
Operating system: Darwin x64 19.5.0 (darwin)

**Comment by brainchild0** [comment]
Please provide a sequence of steps that cause the problem to occur each time you follow those steps.  Otherwise, it is unlikely that anyone would find the reason for the problem.

**Comment by Jocs** [comment]
Closing — this crash was reported against the legacy webpack-bundled build (the stack trace points into `dist/electron/renderer.js` / `dist/electron/main.js` / `webpack:/marktext/...`, which no longer exists).

The renderer + main process were rewritten on top of electron-vite in [PR #4001](https://github.com/marktext/marktext/pull/4001) (commit 85607dd2, shipped in 0.18.x). Many of the crash sites referenced in stacks like this were either rewritten, replaced, or now sit behind explicit guards. The general "Unexpected error" surface was also re-audited and given regression tests in [PR #4268](https://github.com/marktext/marktext/pull/4268).

**Please upgrade to the latest 0.18.x build. If you still hit a crash on a recent build, please reopen with the new MarkText version and the steps that triggered it — the new stack traces will point us to the actual current code.**
