### ISSUE TITLE
Unexpected error: Config schema violation: `spellcheckerLanguage` should match pattern "^[a-z]{2}(?:[-][A-Z]{2})?$"

### ISSUE THREAD

**Issue by Magwit** [marktext/marktext#2280]
### Description

An unexpected error occurred in the main process.

### Stack Trace

```
Error: Config schema violation: `spellcheckerLanguage` should match pattern "^[a-z]{2}(?:[-][A-Z]{2})?$"
    at ElectronStore._validate (C:\Program Files\Mark Text\resources\app.asar\node_modules\conf\index.js:154:10)
    at ElectronStore.set store [as store] (C:\Program Files\Mark Text\resources\app.asar\node_modules\conf\index.js:460:8)
    at ElectronStore.set (C:\Program Files\Mark Text\resources\app.asar\node_modules\conf\index.js:339:14)
    at Yt.setItem (C:\Program Files\Mark Text\resources\app.asar\dist\electron\main.js:2:293546)
    at C:\Program Files\Mark Text\resources\app.asar\dist\electron\main.js:2:293633
    at Array.map (<anonymous>)
    at Yt.setItems (C:\Program Files\Mark Text\resources\app.asar\dist\electron\main.js:2:293620)
    at IpcMainImpl.<anonymous> (C:\Program Files\Mark Text\resources\app.asar\dist\electron\main.js:2:294075)
    at IpcMainImpl.emit (events.js:210:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3908:15)
```

### Version

Mark Text: v0.16.2
Operating system: Windows_NT x64 10.0.18362 (win32)

**Comment by brainchild0** [comment]
Would you please provide the steps that reproduce the error?

**Comment by Ayfri** [comment]
I have also this error when I activate the spell checker.

**Comment by Magwit** [comment]
The error occured when I activated the spell checker for the very first time. and choosing 'en-029'. I was able to repoduce the error again by deactivating spellckeck and then activating it again with the choice en-029.  (As a sidenote I notive there are all kinds of varieties of English except US English to choose from.) I a have now enabled en-GB and it works fine when I use Mark Text.

**Comment by brainchild0** [comment]
Do you have access to the US dictionary in other applications?  Can you check that your system has the dictionary installed?

@Jocs @fxha: It appears Microsoft has once again [broken compatibility with standards](https://stackoverflow.com/questions/7192410), though this time claiming to do the opposite, by allowing `029` to occur in the country field, representing the Caribbean region. So the regular expression breaks for anyone trying to use the Caribbean   dictionary in Windows.
