### ISSUE TITLE
Opening implicit URL fails on Mac OS Catalina

### ISSUE THREAD

**Issue by cmantoux** [marktext/marktext#2319]
### Description

This error occurs when I try to open a link written under the form `[https://www.google.com]()`. The link does not open and the following error shows. I have no problem opening "explicit" URLs like `[Google](https://www.google.com)`.

### Stack Trace

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)
    at Object.isAbsolute (path.js:1030:5)
    at IpcMainImpl.<anonymous> (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:235097)
    at IpcMainImpl.emit (events.js:210:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3908:15)
    at WebContents.emit (events.js:210:5)
```

### Version

Mark Text: v0.16.2
Operating system: Mac OS Catalina 10.15.6.

**Comment by orbanbalage** [comment]
I have the same issue. Same version of Mark Text; Catalina is 10.15.7.
