### ISSUE TITLE
Unexpected error: Cannot destructure property 'text' of 'n' as it is null.

### ISSUE THREAD

**Issue by Z3r0ish** [marktext/marktext#2338]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
TypeError: Cannot destructure property 'text' of 'n' as it is null.
    at ea.updateParagraph (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/contentState/paragraphCtrl.js:455:13)
    at Nc.selectItem (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/ui/quickInsert/index.js:136:22)
    at Object.call (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/ui/quickInsert/index.js:68:22)
    at invokeHandler (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/node_modules/snabbdom/modules/eventlisteners.js:6:17)
    at handleEvent (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/node_modules/snabbdom/modules/eventlisteners.js:34:9)
    at HTMLDivElement.A (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/node_modules/snabbdom/modules/eventlisteners.js:39:9)
```

### Version

Mark Text: v0.16.2 (fc346d3)
Operating system: Linux x64 5.8.8-arch1-1 (linux)

**Comment by Jocs** [comment]
This issue appears to be a duplicate of #2099.

The original issue: https://github.com/marktext/marktext/issues/2099

Adding the `🦞 resolved/duplicate` label. If you believe this is a distinct issue, please reopen with additional details explaining the difference.

*This comment was added automatically as part of a bulk deduplication pass.*
