### ISSUE TITLE
Unexpected error: Cannot read property 'nodeType' of null

### ISSUE THREAD

**Issue by srevinsaju** [marktext/marktext#2349]
### Description

An unexpected error occurred in the renderer process.

I tried to copy an image to the clipboard using Ctrl + C
PS: I have not checked for duplicated, please feel free to close it in case

### Stack Trace

```
TypeError: Cannot read property 'nodeType' of null
    at getNodeAndOffset (file:///tmp/.mount_marktejVHtBN/resources/app.asar/dist/electron/webpack:/src/muya/lib/selection/index.js:416:16)
    at Object.setCursorRange (file:///tmp/.mount_marktejVHtBN/resources/app.asar/dist/electron/webpack:/src/muya/lib/selection/index.js:482:54)
    at ea.setCursor (file:///tmp/.mount_marktejVHtBN/resources/app.asar/dist/electron/webpack:/src/muya/lib/contentState/index.js:194:15)
    at ea.partialRender (file:///tmp/.mount_marktejVHtBN/resources/app.asar/dist/electron/webpack:/src/muya/lib/contentState/index.js:246:12)
    at ea.cutHandler (file:///tmp/.mount_marktejVHtBN/resources/app.asar/dist/electron/webpack:/src/muya/lib/contentState/copyCutCtrl.js:45:10)
    at HTMLDivElement.n (file:///tmp/.mount_marktejVHtBN/resources/app.asar/dist/electron/webpack:/src/muya/lib/eventHandler/clipboard.js:28:22)
```

### Version

Mark Text: v0.16.2 (c3c45b1)
Operating system: Linux x64 5.8.11-arch1-1 (linux)

**Comment by Jocs** [comment]
Closing — this crash was reported against the legacy webpack-bundled build (the stack trace points into `dist/electron/renderer.js` / `dist/electron/main.js` / `webpack:/marktext/...`, which no longer exists).

The renderer + main process were rewritten on top of electron-vite in [PR #4001](https://github.com/marktext/marktext/pull/4001) (commit 85607dd2, shipped in 0.18.x). Many of the crash sites referenced in stacks like this were either rewritten, replaced, or now sit behind explicit guards. The general "Unexpected error" surface was also re-audited and given regression tests in [PR #4268](https://github.com/marktext/marktext/pull/4268).

**Please upgrade to the latest 0.18.x build. If you still hit a crash on a recent build, please reopen with the new MarkText version and the steps that triggered it — the new stack traces will point us to the actual current code.**
