### ISSUE TITLE
Unexpected error: Cannot read property 'nodeType' of null

### ISSUE THREAD

**Issue by RyanGreenup** [marktext/marktext#2393]
### Description

An unexpected error occurred in the renderer process.

I just tried to delete a table and the app prompted me to report the issue, feel free to close this if you want.

### Stack Trace

```
TypeError: Cannot read property 'nodeType' of null
    at getNodeAndOffset (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/selection/index.js:416:16)
    at Object.setCursorRange (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/selection/index.js:482:54)
    at ea.setCursor (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/contentState/index.js:194:15)
    at ea.partialRender (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/contentState/index.js:246:12)
    at ea.inputHandler (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/contentState/inputCtrl.js:324:51)
    at HTMLDivElement.<anonymous> (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/eventHandler/keyboard.js:203:22)
```

### Version

Mark Text: v0.16.2 (fc346d3)
Operating system: Linux x64 5.9.8-arch1-1 (linux)

**Comment by Jocs** [comment]
This issue appears to be a duplicate of #2349.

The original issue: https://github.com/marktext/marktext/issues/2349

Adding the `🦞 resolved/duplicate` label. If you believe this is a distinct issue, please reopen with additional details explaining the difference.

*This comment was added automatically as part of a bulk deduplication pass.*
