### ISSUE TITLE
Unexpected error: Failed to execute 'setStart' on 'Range': There is no child at offset 73.

### ISSUE THREAD

**Issue by bscadh** [marktext/marktext#2526]
### Description

An unexpected error occurred in the renderer process.

The bug happens once I finished typing the following code:
\<pre\>some text\</pre\>

Even after entering the above text, the bug report shows up when I click on or try to highlight the concerning code.

### Stack Trace

```
Error: Failed to execute 'setStart' on 'Range': There is no child at offset 73.
    at Object.select (file:///tmp/.mount_markteivIQ8J/resources/app.asar/dist/electron/webpack:/src/muya/lib/selection/index.js:346:11)
    at Object.setCursorRange (file:///tmp/.mount_markteivIQ8J/resources/app.asar/dist/electron/webpack:/src/muya/lib/selection/index.js:491:10)
    at aa.setCursor (file:///tmp/.mount_markteivIQ8J/resources/app.asar/dist/electron/webpack:/src/muya/lib/contentState/index.js:205:15)
    at aa.partialRender (file:///tmp/.mount_markteivIQ8J/resources/app.asar/dist/electron/webpack:/src/muya/lib/contentState/index.js:257:12)
    at aa.inputHandler (file:///tmp/.mount_markteivIQ8J/resources/app.asar/dist/electron/webpack:/src/muya/lib/contentState/inputCtrl.js:324:51)
    at HTMLDivElement.<anonymous> (file:///tmp/.mount_markteivIQ8J/resources/app.asar/dist/electron/webpack:/src/muya/lib/eventHandler/keyboard.js:203:22)
```

### Version

Mark Text: v0.16.3 (0fa6c33c)
Operating system: Linux x64 5.4.0-66-lowlatency (linux)

**Comment by Jocs** [comment]
Closing this with the regression-guard e2e specs added in https://github.com/marktext/marktext/pull/4268.

The user-action recipe described here (and the same crash signature in ~25 other reports) does not reproduce on the current `develop` branch (0.18.9). The setCursorRange offset clamp at `src/muya/lib/selection/index.js:524-530` plus cumulative refactor fixes appear to have closed the underlying bug.

The recipes from these reports are now encoded as Playwright tests in `test/e2e/crash-range-offset.spec.ts` so a regression here will fail CI before it reaches another user.

**If you still hit this crash on a recent build, please reopen with the exact MarkText version and the markdown that triggered it.**
