### ISSUE TITLE
Unexpected error: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by lucknaumann** [marktext/marktext#2530]
### Description

An unexpected error occurred in the main process.

### Stack Trace

```
TypeError: Cannot read property 'id' of undefined
    at Xe (C:\Ketarin\Office\Mark Text (x64)\resources\app.asar\dist\electron\main.js:2:246076)
    at click (C:\Ketarin\Office\Mark Text (x64)\resources\app.asar\dist\electron\main.js:2:264249)
    at MenuItem.click (electron/js2c/browser_init.js:73:1683)
    at Object.a._executeCommand (electron/js2c/browser_init.js:81:2343)
```

### Version

Mark Text: v0.16.3
Operating system: Windows_NT ia32 10.0.19042 (win32)

Obviously, this is an error message I just got but could be my system and not the program itself. I was trying to open a recent file when this popup error occurred. However, everything seems fine now. And, while I'm here, thanks for this great program! 😃

**Comment by Jocs** [comment]
Closing — this crash was reported against the legacy webpack-bundled build (the stack trace points into `dist/electron/renderer.js` / `dist/electron/main.js` / `webpack:/marktext/...`, which no longer exists).

The renderer + main process were rewritten on top of electron-vite in [PR #4001](https://github.com/marktext/marktext/pull/4001) (commit 85607dd2, shipped in 0.18.x). Many of the crash sites referenced in stacks like this were either rewritten, replaced, or now sit behind explicit guards. The general "Unexpected error" surface was also re-audited and given regression tests in [PR #4268](https://github.com/marktext/marktext/pull/4268).

**Please upgrade to the latest 0.18.x build. If you still hit a crash on a recent build, please reopen with the new MarkText version and the steps that triggered it — the new stack traces will point us to the actual current code.**
