### ISSUE TITLE
Unexpected error: net::ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by sa-tasche** [marktext/marktext#2531]
### Description

An unexpected error occurred in the main process.

### Stack Trace

```
Error: net::ERR_CONNECTION_RESET
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2519:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
```

### Version

Mark Text: v0.16.1
Operating system: Windows_NT x64 10.0.19042 (win32)

**Comment by Jocs** [comment]
Closing — this is a transient network error from the auto-updater's HTTPS request (`SimpleURLLoaderWrapper` in `electron/js2c/browser_init.js`), not an actionable bug in MarkText itself. ERR_HTTP2_PROTOCOL_ERROR / ERR_CONNECTION_RESET / ERR_CONNECTION_CLOSED are surfaced by Chromium's net stack when the upstream connection drops mid-fetch.

**If this is reproducible (vs. a one-off you saw once), please reopen with: your MarkText version, whether it happens on every update check or only sometimes, and ideally a packet capture or proxy/firewall configuration — there's not much we can do from the app side without that information.**
