### ISSUE TITLE
Unexpected error: callback can only be called for once

### ISSUE THREAD

**Issue by s78785978** [marktext/marktext#2551]
### Description

An unexpected error occurred in the main process.

### Stack Trace

```
TypeError: callback can only be called for once
    at Object.module.<computed> [as getPrimaryDisplay] (electron/js2c/browser_init.js:6950:30)
    at /Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:304384
    at Ut.createWindow (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:304768)
    at jt._createEditorWindow (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:315178)
    at jt.ready (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:313119)
    at App.<anonymous> (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:314274)
    at App.emit (events.js:210:5)
```

### Version

Mark Text: v0.16.1
Operating system: Darwin x64 20.3.0 (darwin)

**Comment by Jocs** [comment]
This issue appears to be a duplicate of #2203.

The original issue: https://github.com/marktext/marktext/issues/2203

Adding the `🦞 resolved/duplicate` label. If you believe this is a distinct issue, please reopen with additional details explaining the difference.

*This comment was added automatically as part of a bulk deduplication pass.*
