### ISSUE TITLE
gyp ERR! stack Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by hanmant83** [marktext/marktext#2555]
cannot build optional native dependency  name=fs-xattr
                                            version=0.3.1
                                            cause=exit status 1
                                            out=yarn run v1.22.10
$ node-gyp rebuild
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

                                            errorOut=gyp info it worked if it ends with ok
   gyp info using node-gyp@5.0.5
   gyp info using node@12.13.0 | linux | x64
   gyp info find Python using Python version 2.7.17 found at "/usr/bin/python"
   gyp http GET https://electronjs.org/headers/v8.2.5/node-v8.2.5-headers.tar.gz
   gyp WARN install got an error, rolling back install
   gyp ERR! configure error
   gyp ERR! stack Error: unable to get local issuer certificate
   gyp ERR! stack     at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
   gyp ERR! stack     at TLSSocket.emit (events.js:210:5)
   gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:794:8)
   gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12)
   gyp ERR! System Linux 4.15.0-140-generic
   gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
   gyp ERR! cwd /home/hanmant.shinde/Hanamnt/Signal-Desktop/node_modules/fs-xattr
   gyp ERR! node -v v12.13.0

**Comment by Jocs** [comment]
This build error is specific to older toolchain configurations using npm/yarn. The project now requires **Node.js ≥20.19.0** and **pnpm@10.33.4**. Please retry with the current setup:
```bash
pnpm install
pnpm run dev
```
Closing as outdated environment.
