### ISSUE TITLE
Unexpected error: Cannot destructure property 'text' of 'n' as it is null.

### ISSUE THREAD

**Issue by Gokuldroid** [marktext/marktext#2593]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
TypeError: Cannot destructure property 'text' of 'n' as it is null.
    at aa.Yr.A.updateParagraph (file:///Applications/Mark%20Text.app/Contents/Resources/app.asar/dist/electron/renderer.js:21:2641209)
    at Hc.selectItem (file:///Applications/Mark%20Text.app/Contents/Resources/app.asar/dist/electron/renderer.js:45:29984)
    at HTMLDivElement.<anonymous> (file:///Applications/Mark%20Text.app/Contents/Resources/app.asar/dist/electron/renderer.js:45:25122)
```

### Version

Mark Text: v0.16.3 (9dc8469a)
Operating system: Darwin x64 19.6.0 (darwin)

**Comment by Jocs** [comment]
This issue appears to be a duplicate of #2099.

The original issue: https://github.com/marktext/marktext/issues/2099

Adding the `🦞 resolved/duplicate` label. If you believe this is a distinct issue, please reopen with additional details explaining the difference.

*This comment was added automatically as part of a bulk deduplication pass.*
