### ISSUE TITLE
he 'screen' module can't be used before the app 'ready' event after opening it

### ISSUE THREAD

**Issue by pajarnas** [marktext/marktext#2604]
M1 Chip macOS Big Sur 11.4 

Error: The 'screen' module can't be used before the app 'ready' event
at createScreenIfNeeded (electron/js2c/browser_init.js:125:261)
at Object.get (electron/js2c/browser_init.js:125:303)
at /Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:278648
at Wt.createWindow (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:279032)
at zt._createEditorWindow (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:289184)
at zt.ready (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:287462)
at App.<anonymous> (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:288617)
at App.emit (events.js:315:20)

**Comment by pajarnas** [comment]
It is downloaded from 0.16.3 release, mark text mac.zip

**Comment by Jocs** [comment]
Thank you for the report! This crash was caused by an Electron compatibility issue with early Apple Silicon (M1) support that affected Electron 12-era builds. The current version of MarkText uses Electron 42, which has full native Apple Silicon support and this bug has long since been resolved in the Electron runtime. Please try the latest version — if you still see this crash, feel free to reopen with details about your OS version and where you downloaded the app.
