### ISSUE TITLE
yarn install failed

### ISSUE THREAD

**Issue by garrett12138** [marktext/marktext#2669]
### Question description
env:
os : windows 10 
node : v14.17.0
yarn : v1.22.17

run yarn install failed,console output : 

yarn install
yarn install v1.22.17
$ node .electron-vue/preinstall.js
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > eslint-plugin-vue@6.2.2" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
[4/4] Building fresh packages...
$ yarn run rebuild && yarn run lint:fix
yarn run v1.22.17
$ electron-rebuild -f
/ Building module: spellchecker, Completed: 0gyp info find Python using Python version 2.7.17 found at "C:\Python27\python.exe"
- Building module: spellchecker, Completed: 0gyp http GET https://www.electronjs.org/headers/v11.1.1/node-v11.1.1-headers.tar.gz
| Building module: spellchecker, Completed: 0gyp http 200 https://www.electronjs.org/headers/v11.1.1/node-v11.1.1-headers.tar.gz
- Building module: spellchecker, Completed: 0gyp http GET https://www.electronjs.org/headers/v11.1.1/SHASUMS256.txt
gyp http GET https://www.electronjs.org/headers/v11.1.1/win-x86/node.lib
gyp http GET https://www.electronjs.org/headers/v11.1.1/win-x64/node.lib
gyp http GET https://www.electronjs.org/headers/v11.1.1/win-arm64/node.lib
- Building module: spellchecker, Completed: 0gyp http 200 https://www.electronjs.org/headers/v11.1.1/win-x64/node.lib
gyp http 200 https://www.electronjs.org/headers/v11.1.1/win-arm64/node.lib
\ Building module: spellchecker, Completed: 0gyp http 200 https://www.electronjs.org/headers/v11.1.1/SHASUMS256.txt
gyp http 200 https://www.electronjs.org/headers/v11.1.1/win-x86/node.lib
| Building module: spellchecker, Completed: 0gyp info find VS using VS2015 (14.0) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python27\python.exe
gyp info spawn args [
gyp info spawn args   'E:\\code\\electron\\marktext\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\code\\electron\\marktext\\node_modules\\@hfelix\\spellchecker\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\code\\electron\\marktext\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\code\\electron\\marktext\\node_modules\\@hfelix\\spellchecker\\11.1.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=E:\\code\\electron\\marktext\\node_modules\\@hfelix\\spellchecker\\11.1.1',
gyp info spawn args   '-Dnode_gyp_dir=E:\\code\\electron\\marktext\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=E:\\\\code\\\\electron\\\\marktext\\\\node_modules\\\\@hfelix\\\\spellchecker\\\\11.1.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\code\\electron\\marktext\\node_modules\\@hfelix\\spellchecker',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\code\\electron\\marktext\\node_modules\\@hfelix\\spellchecker\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
| Building module: spellchecker, Completed: 0Warning: Missing input files:
E:\code\electron\marktext\node_modules\@hfelix\spellchecker\build\..\vendor\hunspell\src\build\build.h
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64',
gyp info spawn args   map: [Function (anonymous)]
gyp info spawn args ]
/ Building module: spellchecker, Completed: 0在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
| Building module: spellchecker, Completed: 0  md5.cc
| Building module: spellchecker, Completed: 0  string_piece.cc
| Building module: spellchecker, Completed: 0  bdict_reader.cc
| Building module: spellchecker, Completed: 0  bdict.cc
\ Building module: spellchecker, Completed: 0  affentry.cxx
\ Building module: spellchecker, Completed: 0  affixmgr.cxx
\ Building module: spellchecker, Completed: 0  csutil.cxx
\ Building module: spellchecker, Completed: 0  dictmgr.cxx
/ Building module: spellchecker, Completed: 0  filemgr.cxx
| Building module: spellchecker, Completed: 0  hashmgr.cxx
| Building module: spellchecker, Completed: 0  hunspell.cxx
| Building module: spellchecker, Completed: 0  hunzip.cxx
/ Building module: spellchecker, Completed: 0  phonet.cxx
\ Building module: spellchecker, Completed: 0  replist.cxx
/ Building module: spellchecker, Completed: 0  suggestmgr.cxx
| Building module: spellchecker, Completed: 0  textparser.cxx
- Building module: spellchecker, Completed: 0  win_delay_load_hook.cc
/ Building module: spellchecker, Completed: 0  hunspell.vcxproj -> E:\code\electron\marktext\node_modules\@hfelix\spellchecker\build\Release\\hunspell.lib
- Building module: spellchecker, Completed: 0  main.cc
| Building module: spellchecker, Completed: 0..\src\main.cc(196): error C2248: 'Napi::Env::DefaultFini': cannot access private member declared in class 'Napi::Env'
[E:\code\electron\marktext\node_modules\@hfelix\spellchecker\build\spellchecker.vcxproj]
  e:\code\electron\marktext\node_modules\node-addon-api\napi-inl.h(436): note: see declaration of 'Napi::Env::DefaultFi
  ni'
  E:\code\electron\marktext\node_modules\node-addon-api\napi.h(168): note: see declaration of 'Napi::Env'
× Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild 'E:\code\electron\marktext\node_modules\@hfelix\spellchecker'.
Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1

Error: node-gyp failed to rebuild 'E:\code\electron\marktext\node_modules\@hfelix\spellchecker'.
Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1

    at ModuleRebuilder.rebuildNodeGypModule (E:\code\electron\marktext\node_modules\electron-rebuild\lib\src\module-rebuilder.js:193:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Rebuilder.rebuildModuleAt (E:\code\electron\marktext\node_modules\electron-rebuild\lib\src\rebuild.js:190:9)
    at async Rebuilder.rebuild (E:\code\electron\marktext\node_modules\electron-rebuild\lib\src\rebuild.js:152:17)
    at async E:\code\electron\marktext\node_modules\electron-rebuild\lib\src\cli.js:146:9
error Command failed with exit code 4294967295.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 4294967295.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by Jocs** [comment]
@garrett12138 Do you have resolved this issue?

**Comment by Jocs** [comment]
This error is caused by using Node.js v14 and yarn 1.22, both of which are no longer supported. The project now requires **Node.js ≥20.19.0** and **pnpm@10.33.4**:
```bash
pnpm install
pnpm run dev
```
Closing as outdated environment.
