### ISSUE TITLE
Error: Module did not self-register:

### ISSUE THREAD

**Issue by y2276789113** [marktext/marktext#2703]
### Question description
dev mode 

```
Error: Module did not self-register: '/Users/pan/marktext/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node'.
      at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
      at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
      at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
      at Module.load (internal/modules/cjs/loader.js:935:32)
      at Module._load (internal/modules/cjs/loader.js:776:14)
      at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
      at Module.require (internal/modules/cjs/loader.js:959:19)
      at require (internal/modules/cjs/helpers.js:88:18)
      at Object.<anonymous> (/Users/pan/marktext/node_modules/keyboard-layout/lib/keyboard-layout.js:4:35)
      at Module._compile (internal/modules/cjs/loader.js:1078:30)
  
┗ ----------------------------

┏ Electron -------------------

  
  DevTools listening on ws://127.0.0.1:8315/devtools/browser/926c01ef-1be8-49ce-b45f-cbdd2ce8d155
  
┗ ----------------------------

┏ Electron -------------------

  (node:19989) ExtensionLoadWarning: Warnings loading extension at /Users/pan/Library/Application Support/Electron/extensions/nhdogjmejiglipccpnnnanhbledajbpd:
    Unrecognized manifest key 'browser_action'.
    Unrecognized manifest key 'update_url'.
    Permission 'contextMenus' is unknown or URL pattern is malformed.
    Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.
  
  (Use `Electron --trace-warnings ...` to show where the warning was created)
  
┗ ----------------------------

```

**Comment by Jocs** [comment]
@y2276789113 Do you solved this issue?

**Comment by Jocs** [comment]
Thanks for the report! This error means the `keyboard-layout` native module wasn't rebuilt against Electron's ABI in your local dev setup — an environment/build issue rather than an app bug. Since this was filed (2021), the build system has been substantially reworked: the `keyboard-layout` dependency no longer exists, it's been replaced by `native-keymap`, and there's now a dedicated postinstall step (`scripts/postinstall.ts`) that restores the native source, downloads Electron, and runs `electron-rebuild` automatically. A fresh `pnpm install` on the current `develop` should set this up correctly. I'm going to close this as it's no longer reproducible on the current codebase, but please reopen with details if you still hit a native-module error after a clean install on the latest source.

**Comment by Jocs** [comment]
Thanks for the report! This error means the `keyboard-layout` native module wasn't rebuilt against Electron's ABI in your local dev setup — an environment/build issue rather than an app bug. Since this was filed (2021), the build system has been substantially reworked: the `keyboard-layout` dependency no longer exists, it's been replaced by `native-keymap`, and there's now a dedicated postinstall step (`scripts/postinstall.ts`) that restores the native source, downloads Electron, and runs `electron-rebuild` automatically. A fresh `pnpm install` on the current `develop` should set this up correctly. I'm going to close this as it's no longer reproducible on the current codebase, but please reopen with details if you still hit a native-module error after a clean install on the latest source.
