### ISSUE TITLE
npm run dev  Err : TypeError: Cannot read property 'aidou' of null

### ISSUE THREAD

**Issue by codeofjackie** [marktext/marktext#283]
### Error happened when `npm run dev`

**Error information**

 TypeError: Cannot read property 'aidou' of null
      at Object.<anonymous> (E:\Web开发\marktext\dist\electron\main.js:17115:35)
      at __webpack_require__ (E:\Web开发\marktext\dist\electron\main.js:21:30)
      at Object.module.exports.exports.__esModule (E:\Web开发\marktext\dist\electron\main.js:16973:64)
      at __webpack_require__ (E:\Web开发\marktext\dist\electron\main.js:21:30)
      at Object.<anonymous> (E:\Web开发\marktext\dist\electron\main.js:2990:65)
      at __webpack_require__ (E:\Web开发\marktext\dist\electron\main.js:21:30)
      at Object.<anonymous> (E:\Web开发\marktext\dist\electron\main.js:1804:64)
      at Object.module.exports.EXTENSIONS (E:\Web开发\marktext\dist\electron\main.js:1936:30)
      at __webpack_require__ (E:\Web开发\marktext\dist\electron\main.js:21:30)
      at Object.module.exports.module.exports.value.value (E:\Web开发\marktext\dist\electron\main.js:8389:72)

### Steps to reproduce

> cd marktext
> npm install
> npm run dev

**Expected behavior:** An Electron App/window will be popup.

**Actual behavior:** Error happened in the terminal?

### Versions

- Mark Text: 0.10.21
- OS: Win10 1804
- npm 5.6.0
- node 8.10.0

**Comment by Jocs** [comment]
@codeofjackie I update the description of this issue, so that other member can understand what this issue about.

**Comment by fxha** [comment]
Yes, it's a fatal exception in main process on Windows because `aidou` is `null`. At the moment we cannot execute the Windows binary. I'll take a look at this later.

@Jocs We should integrate AppVeyor (Windows CI) and execute Mark Text on Travis CI and AppVeyor to detect these problems. I'll open an issue for updating CI's later.

**Comment by Jocs** [comment]
@fxha So this is a bug?

**Comment by fxha** [comment]
@Jocs Yes; we cannot use Mark Text on Windows because of app crash.

**Comment by Jocs** [comment]
@fxha Ok, I'll label this issue with `bug`.

**Comment by codeofjackie** [comment]
@fxha Thanks! So……this application was developing under the Mac or Linux before?

**Comment by fxha** [comment]
@codeofjackie No, Mark Text is cross-plattfrom (Linux, macOS and Windows) but mainly developed on macOS and Linux.

@Jocs @codeofjackie 

Strange problem: If you use the default git configuration on Windows, it will convert all files to CRLF line ending. The used RegEx (which removes all new lines before parsing) replaced only LF, not CRLF. My git configuration was configured with LF so that the problem did not occur. This problem should be fixed with #284.
