### ISSUE TITLE
Unexpected error: Failed to execute 'setStart' on 'Range': The offset 4294967292 is invalid.

### ISSUE THREAD

**Issue by pavkam** [marktext/marktext#2874]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
Error: Failed to execute 'setStart' on 'Range': The offset 4294967292 is invalid.
    at Object.select (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/selection/index.js:346:11)
    at Object.setCursorRange (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/selection/index.js:491:10)
    at aa.setCursor (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/contentState/index.js:205:15)
    at aa.render (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/contentState/index.js:235:12)
    at aa.enterHandler (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/contentState/enterCtrl.js:546:26)
    at HTMLDivElement.<anonymous> (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/eventHandler/keyboard.js:175:26)
```

### Version

Mark Text: v0.16.3 (ed052b8)
Operating system: Linux x64 5.9.16-1-MANJARO (linux)

**Comment by fxha** [comment]
Thank you for reporting the issue. We noticed that this is a duplicate and closing it in favor of #2627. You may want to subscribe there for further updates.
