### ISSUE TITLE
Unexpected error: Cannot read property 'text' of null

### ISSUE THREAD

**Issue by plum** [marktext/marktext#2925]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
TypeError: Cannot read property 'text' of null
    at aa.checkNeedRender (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/contentState/updateCtrl.js:33:46)
    at aa.clickHandler (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/contentState/clickCtrl.js:178:35)
    at HTMLDivElement.<anonymous> (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/eventHandler/clickEvent.js:230:20)
```

### Version

Mark Text: v0.16.3 (ed052b8)
Operating system: Linux x64 5.15.14-1-lts (linux)

**Comment by Jocs** [comment]
How to reproduce this issue?

**Comment by plum** [comment]
This happens when in typewriter mode, under a heading , such as H3,  with a nested , when attempting to re-organise that list, 
possibly when attempting back space deletions. It has happened several times.

I usually have to close the file and re-open it, to stop it happening immediately after it first occurs, upon forlexampke a save command.
The editing will proceed smoothly again, and save operations too.

I was able to repeat it just one minute ago for our purpose, on a file.. However , trying once again to repeat it  I can't seem to do so.  I thinks therefore  I may be able to be even more specific by paying closer attention to the exact layout my text and, operations, next time. I shall report back with further observation.

Regards,
John
....
Running MarkText 0.16.3-3  latest build, from aur repository on linux-lts 5.15.16-1

**Comment by Jocs** [comment]
This issue appears to be a duplicate of #2629.

The original issue: https://github.com/marktext/marktext/issues/2629

Adding the `🦞 resolved/duplicate` label. If you believe this is a distinct issue, please reopen with additional details explaining the difference.

*This comment was added automatically as part of a bulk deduplication pass.*
