### ISSUE TITLE
Unexpected error: Cannot read property 'nodeType' of null

### ISSUE THREAD

**Issue by plum** [marktext/marktext#2950]
### Description

An unexpected error occurred in the renderer process.

I closed one tab of three open, by clicking on the tab 'x' icon. A dialogue came up asking ot save changes, and I pressed 'save'. This action returned the next open tab to the main view; that's when the error message came up.

The tab which returned to the main view had  20 lines in all in the file, some with list indentations up to two levels. 
All 20 lines were selected (i.e. select all), highlighted in blue. That surprised me a little, as I do not blelieve I had selected them for any operation.
......
Arch, linux-lts 5.15.16-1

### Stack Trace

```
TypeError: Cannot read property 'nodeType' of null
    at getNodeAndOffset (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/selection/index.js:416:16)
    at Object.setCursorRange (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/selection/index.js:483:52)
    at aa.setCursor (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/contentState/index.js:205:15)
    at aa.partialRender (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/contentState/index.js:257:12)
    at aa.clickHandler (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/contentState/clickCtrl.js:182:19)
    at HTMLDivElement.<anonymous> (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/eventHandler/clickEvent.js:230:20)
```

### Version

Mark Text: v0.16.3 (ed052b8)
Operating system: Linux x64 5.15.16-1-lts (linux)

**Comment by Jocs** [comment]
This issue appears to be a duplicate of #2349.

The original issue: https://github.com/marktext/marktext/issues/2349

Adding the `🦞 resolved/duplicate` label. If you believe this is a distinct issue, please reopen with additional details explaining the difference.

*This comment was added automatically as part of a bulk deduplication pass.*
