### ISSUE TITLE
Editor crash: Failed to execute 'setAttributeNS' on 'Element'

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#2979]
### Description

An exception occurs if you open a SVG with `xmlns:xlink` attribute.

### Steps to reproduce

Open the given file below.

**Expected behavior:**

The SVG should be rendered or ignored.

**Actual behavior:**

Exception in Muya that causes follow-up issues that may crash the complete editor.

**Stack Trace:**

```
DOMException: Failed to execute 'setAttributeNS' on 'Element': 'http://www.w3.org/1999/xlink' is an invalid namespace for attributes.
    at Array.updateAttrs (./node_modules/snabbdom/build/snabbdom.cjs.js:711:25)
    at createElm (./node_modules/snabbdom/build/snabbdom.cjs.js:208:30)
    at createElm (./node_modules/snabbdom/build/snabbdom.cjs.js:213:46)
    at createElm (./node_modules/snabbdom/build/snabbdom.cjs.js:213:46)
    at updateChildren (./node_modules/snabbdom/build/snabbdom.cjs.js:355:49)
    at patchVnode (./node_modules/snabbdom/build/snabbdom.cjs.js:396:21)
    at patch (./node_modules/snabbdom/build/snabbdom.cjs.js:430:13)
    at ia.render (file://./dist/electron/webpack:/marktext/src/muya/lib/parser/render/index.js:183:5)
    at Ss.render (file://./dist/electron/webpack:/marktext/src/muya/lib/contentState/index.js:233:22)
    at Os.setMarkdown (file://./dist/electron/webpack:/marktext/src/muya/lib/index.js:178:23)
```

Followed by:

```
TypeError: Cannot read properties of null (reading 'type')
    at filter (./dist/electron/webpack:/marktext/src/muya/lib/contentState/paragraphCtrl.js:30)
    at Array.filter (<anonymous>)
    at Ss.selectionChange (./dist/electron/webpack:/marktext/src/muya/lib/contentState/paragraphCtrl.js:30)
    at Os.getSelection (./dist/electron/webpack:/marktext/src/muya/lib/index.js:196)
    at a.call (./dist/electron/webpack:/marktext/src/renderer/components/editorWithTabs/editor.vue:1055)
    at Array.i (./dist/electron/webpack:/marktext/node_modules/vue/dist/vue.esm.js:1998)
    at Je (./dist/electron/webpack:/marktext/node_modules/vue/dist/vue.esm.js:1924)
```

**Example file:**

```md
Test SVG

<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">
  <a>
    <text x="10" y="25">An example link.</text>
  </a>
</svg>

EOF
```

### Versions

- Mark Text: 0.16.3, 0.17.0-rc
- Operating system: all

**Comment by Jocs** [comment]
Thank you for this detailed bug report. This crash was caused by snabbdom's `attributesModule` calling `setAttributeNS` when reconciling virtual DOM nodes that contained `xmlns:xlink` attributes from SVG content — a path that existed in the old muya engine (muyajs).

The editor engine has since been rewritten (`@muyajs/core`, `packages/muya`). The new engine's HTML-block preview (`packages/muya/src/block/commonMark/html/htmlPreview.ts`) no longer routes HTML block content through snabbdom at all: it sanitizes with DOMPurify (with SVG profiles enabled) and assigns the result directly to `innerHTML`. The `setAttributeNS` crash path no longer exists.

Closing as resolved by the engine migration. If you can reproduce this in a recent build, please reopen with version details and a test file.
