### ISSUE TITLE
Portable mode does not work fully with commandline

### ISSUE THREAD

**Issue by Cyberklabauter** [marktext/marktext#3020]
### Description

I use MarktText portable (Call MarkText.exe --user-data-dir Data). If I try to launch/open more than one document it fails with the following error message:

> An unexpected error occurred in the main process
> ArgError: option requires argument: --user-data-dir
>     at arg (P:\PortableApps\PortableApps\MarkTextP\App\resources\app.asar\node_modules\arg\index.js:127:13)
>     at E (P:\PortableApps\PortableApps\MarkTextP\App\resources\app.asar\dist\electron\main.js:2:226395)
>     at App.<anonymous> (P:\PortableApps\PortableApps\MarkTextP\App\resources\app.asar\dist\electron\main.js:2:288093)
>     at App.emit (events.js:315:20)

Can you reproduce the issue? `
- [x] yes
- [ ] no

### Steps to reproduce

1. Open a document using
`Call MarkText.exe .\TestDoc1.md --user-data-dir .\Data`
2. Open a second document using
`Call MarkText.exe .\TestDoc2.md --user-data-dir .\Data`

It fails with the error message (see above). 

If I skip the definition of setting directory in step 2 using
`Call MarkText.exe .\TestDoc2.md `
it creates a new setting dir in %AppData% and launches a second instance instead of a new tab (because of the start of the non-portable version)

see above

**Expected behavior:**

Open the second, third, ... document in the in a new tab of the same instance. 

**Actual behavior:**

Fails with the error message 

**Link to an example: [optional]**

### Versions

- MarkText version: 16.3 (portable)
- Operating system: Win 10

**Comment by Cyberklabauter** [comment]
Thank you for digging into that. I hope electron will fix that.

**Comment by Cyberklabauter** [comment]
Thank you Felix for fixing that in a future version. I agree that this bothers only a smaller group of users. 

One of the great things about marktext is, that this app works portable and for that it would be fantastic to have this commandline option to integrate marktext in a portable eco system. 

I  will wait patiently for version 0.18.

**Comment by Jocs** [comment]
This still happens on the current development build, and #5375 fixes it. Electron (see electron/electron#32933) hands the running instance a reordered command line from the second instance, with switches first and a few switches of its own appended. `--user-data-dir .\Data` is therefore separated from its value and fails to parse.

Until a release includes the fix, write the option with `=` so the value stays attached:

```
MarkText.exe .\TestDoc2.md --user-data-dir=.\Data
```

The second document then opens in a new tab of the running instance.
