### ISSUE TITLE
Unexpected error: Cannot read property 'nodeType' of null

### ISSUE THREAD

**Issue by danlynn** [marktext/marktext#3157]
### Description

An unexpected error occurred in the renderer process.

Deleted a selection of text that included headers and lists.

### Stack Trace

```
TypeError: Cannot read property 'nodeType' of null
    at getNodeAndOffset (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/selection/index.js:416:16)
    at Object.setCursorRange (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/selection/index.js:482:54)
    at aa.setCursor (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/contentState/index.js:205:15)
    at aa.partialRender (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/contentState/index.js:257:12)
    at aa.inputHandler (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/contentState/inputCtrl.js:324:51)
    at HTMLDivElement.<anonymous> (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/src/muya/lib/eventHandler/keyboard.js:203:22)
```

### Version

Mark Text: v0.16.3 (9873fac)
Operating system: Linux x64 5.16.16-zen1-1-zen (linux)

**Comment by Jocs** [comment]
This issue appears to be a duplicate of #2349.

The original issue: https://github.com/marktext/marktext/issues/2349

Adding the `🦞 resolved/duplicate` label. If you believe this is a distinct issue, please reopen with additional details explaining the difference.

*This comment was added automatically as part of a bulk deduplication pass.*
