### ISSUE TITLE
[Manjaro] Can not build the Marktext AUR package.

### ISSUE THREAD

**Issue by agoodfellow123** [marktext/marktext#3165]
### Description

After I entered "yay -S marktext" everything goes fine but after the "OKAY  take it away electron-builder yarn run v1.22.17" part it gives an error. The error description is rather vague it just says "⨯ cannot execute  cause=exit status 1".

- [x] Can you reproduce the issue?

### Steps to reproduce

1. Type "yay -S marktext" to your terminal.

**Expected behavior:** To program to install.

**Actual behavior:** Building error.

### Versions

- MarkText version: 0.17.1-1
- Operating system: Manjaro Linux

**Comment by abuGit** [comment]
I have the same installation error.

Tried with yay `yay -S marktext` and 

```
git clone https://aur.archlinux.org/marktext.git
makepkg -s
```
Buidling error:

```
yarn run v1.22.18
$ /home/<MYUSERNAME>/Coding/marktext/src/marktext-0.17.1/node_modules/.bin/electron-builder --linux --x64 --dir
  • electron-builder  version=22.14.13 os=5.16.16-arch1-1
  • loaded configuration  file=/home/<MYUSERNAME>/Coding/marktext/src/marktext-0.17.1/electron-builder.yml
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config  file=build/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=@hfelix/spellchecker@4.1.0, ced@2.0.0, cld@2.7.1, fontmanager-redux@1.1.0, keyboard-layout@2.0.17, keytar@7.9.0, native-keymap@3.2.1 platform=linux arch=x64
  • rebuilding native dependency  name=ced version=2.0.0
  • rebuilding native dependency  name=@hfelix/spellchecker version=4.1.0
  • rebuilding native dependency  name=cld version=2.7.1
  • rebuilding native dependency  name=fontmanager-redux version=1.1.0
  • rebuilding native dependency  name=keyboard-layout version=2.0.17
  • rebuilding native dependency  name=keytar version=7.9.0
  • rebuilding native dependency  name=native-keymap version=3.2.1
  • packaging       platform=linux arch=x64 electron=15.4.2 appOutDir=build/linux-unpacked
  • copying Electron  source=/usr/bin destination=/home/<MYUSERNAME>/Coding/marktext/src/marktext-0.17.1/build/linux-unpacked
  ⨯ EACCES: permission denied, copyfile '/usr/bin/fcrontab' -> '/home/<MYUSERNAME>/Coding/marktext/src/marktext-0.17.1/build/linux-unpacked/fcrontab'  failedTask=build stackTrace=Error: EACCES: permission denied, copyfile '/usr/bin/fcrontab' -> '/home/<MYUSERNAME>/Coding/marktext/src/marktext-0.17.1/build/linux-unpacked/fcrontab'
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at walk (/home/<MYUSERNAME>/Coding/marktext/src/marktext-0.17.1/node_modules/builder-util/src/fs.ts:77:51)
    at unpack (/home/<MYUSERNAME>/Coding/marktext/src/marktext-0.17.1/node_modules/app-builder-lib/src/electron/ElectronFramework.ts:190:5)
    at LinuxPackager.doPack (/home/<MYUSERNAME>/Coding/marktext/src/marktext-0.17.1/node_modules/app-builder-lib/src/platformPackager.ts:233:5)
    at LinuxPackager.pack (/home/<MYUSERNAME>/Coding/marktext/src/marktext-0.17.1/node_modules/app-builder-lib/src/platformPackager.ts:136:5)
    at Packager.doBuild (/home/<MYUSERNAME>/Coding/marktext/src/marktext-0.17.1/node_modules/app-builder-lib/src/packager.ts:441:9)
    at Object.executeFinally (/home/<MYUSERNAME>/Coding/marktext/src/marktext-0.17.1/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/home/<MYUSERNAME>/Coding/marktext/src/marktext-0.17.1/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/home/<MYUSERNAME>/Coding/marktext/src/marktext-0.17.1/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/home/<MYUSERNAME>/Coding/marktext/src/marktext-0.17.1/node_modules/builder-util/src/promise.ts:12:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
==> ERROR: A failure occurred in build().
    Aborting...

```

I have no idea why this guy wants to copy the `/usr/bin/fcrontab' into the building directory ! 
BTW: Installing with `yay -S marktext`and using the option `[2]` (building from bin` works fine.

**But** I think this is an issue for the **AUR**, since deb,rpm, ... packaging works fine. 


## Versions
 - marktext 0.17.1-1
 - Arch Linux 5.16.16-arch1-1

**Comment by fxha** [comment]
Thank you for reporting the issue. We noticed that this seems to be an issue with the distro and the locally install Electron application. Please make sure you're linking against Electron 15.4.0.
