### ISSUE TITLE
Unexpected error: net::ERR_HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by josh-holt** [marktext/marktext#3184]
### Description

An unexpected error occurred in the main process.

To reproduce: check for update from Help menu and download and install.

### Stack Trace

```
Error: net::ERR_HTTP2_PROTOCOL_ERROR
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6497)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
```

### Version

Mark Text: v0.16.3
Operating system: Linux x64 5.13.0-35-generic (linux)

**Comment by Jocs** [comment]
Closing — this is a transient network error from the auto-updater's HTTPS request (`SimpleURLLoaderWrapper` in `electron/js2c/browser_init.js`), not an actionable bug in MarkText itself. ERR_HTTP2_PROTOCOL_ERROR / ERR_CONNECTION_RESET / ERR_CONNECTION_CLOSED are surfaced by Chromium's net stack when the upstream connection drops mid-fetch.

**If this is reproducible (vs. a one-off you saw once), please reopen with: your MarkText version, whether it happens on every update check or only sometimes, and ideally a packet capture or proxy/firewall configuration — there's not much we can do from the app side without that information.**
