### ISSUE TITLE
Unexpected error: net::ERR_HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by Cyan1988** [marktext/marktext#3198]
### Description

An unexpected error occurred in the main process.

### Stack Trace

```
Error: net::ERR_HTTP2_PROTOCOL_ERROR
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6497)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
```

### Version

Mark Text: v0.16.3
Operating system: Windows_NT x64 10.0.22000 (win32)

**Comment by YalandHong** [comment]
#3184

**Comment by Jocs** [comment]
This issue appears to be a duplicate of #3184.

The original issue: https://github.com/marktext/marktext/issues/3184

Adding the `🦞 resolved/duplicate` label. If you believe this is a distinct issue, please reopen with additional details explaining the difference.

*This comment was added automatically as part of a bulk deduplication pass.*
