### ISSUE TITLE
Unexpected error: net::ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by ohmyboy12** [marktext/marktext#3237]
### Description

An unexpected error occurred in the main process.

### Stack Trace

```
Error: net::ERR_CONNECTION_CLOSED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6497)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
```

### Version

Mark Text: v0.16.3
Operating system: Windows_NT x64 10.0.19044 (win32)

**Comment by Jocs** [comment]
Closing — this is a transient network error from the auto-updater's HTTPS request (`SimpleURLLoaderWrapper` in `electron/js2c/browser_init.js`), not an actionable bug in MarkText itself. ERR_HTTP2_PROTOCOL_ERROR / ERR_CONNECTION_RESET / ERR_CONNECTION_CLOSED are surfaced by Chromium's net stack when the upstream connection drops mid-fetch.

**If this is reproducible (vs. a one-off you saw once), please reopen with: your MarkText version, whether it happens on every update check or only sometimes, and ideally a packet capture or proxy/firewall configuration — there's not much we can do from the app side without that information.**

**Comment by ohmyboy12** [comment]
邮件已收到~~我会查看之后回复您
