### ISSUE TITLE
Unexpected error: Cannot read properties of null (reading 'parent')

### ISSUE THREAD

**Issue by tianfeng98** [marktext/marktext#3305]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
TypeError: Cannot read properties of null (reading 'parent')
    at Rs.findOutMostBlock (file:///D:/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/index.js:599:40)
    at Rs.setNextRenderRange (file:///D:/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/index.js:214:36)
    at Rs.partialRender (file:///D:/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/index.js:268:10)
    at Rs.clickHandler (file:///D:/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/clickCtrl.js:185:19)
    at HTMLDivElement.<anonymous> (file:///D:/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/eventHandler/clickEvent.js:233:20)
```

### Version

MarkText: v0.17.1 (2bb405a0)
Operating system: Windows_NT x64 10.0.19044 (win32)

**Comment by tianfeng98** [comment]
> ### Description
> An unexpected error occurred in the renderer process.
> 
> ### Stack Trace
> ```
> TypeError: Cannot read properties of null (reading 'parent')
>     at Rs.findOutMostBlock (file:///D:/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/index.js:599:40)
>     at Rs.setNextRenderRange (file:///D:/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/index.js:214:36)
>     at Rs.partialRender (file:///D:/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/index.js:268:10)
>     at Rs.clickHandler (file:///D:/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/clickCtrl.js:185:19)
>     at HTMLDivElement.<anonymous> (file:///D:/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/eventHandler/clickEvent.js:233:20)
> ```
> 
> ### Version
> MarkText: v0.17.1 ([2bb405a](https://github.com/marktext/marktext/commit/2bb405a03ee52cfba2afe53da4656abb799a0727)) Operating system: Windows_NT x64 10.0.19044 (win32)

使用<kbd>Ctrl</kbd>+<kbd>X</kbd>剪切一大段内容（含标题、超链接、代码块等），剪切未生效，再点击任意段落，就会出现上述报错。

**Comment by Jocs** [comment]
Closing — this crash was reported against the legacy webpack-bundled build (the stack trace points into `dist/electron/renderer.js` / `dist/electron/main.js` / `webpack:/marktext/...`, which no longer exists).

The renderer + main process were rewritten on top of electron-vite in [PR #4001](https://github.com/marktext/marktext/pull/4001) (commit 85607dd2, shipped in 0.18.x). Many of the crash sites referenced in stacks like this were either rewritten, replaced, or now sit behind explicit guards. The general "Unexpected error" surface was also re-audited and given regression tests in [PR #4268](https://github.com/marktext/marktext/pull/4268).

**Please upgrade to the latest 0.18.x build. If you still hit a crash on a recent build, please reopen with the new MarkText version and the steps that triggered it — the new stack traces will point us to the actual current code.**
