### ISSUE TITLE
Unexpected error: Invalid state: all arguments must be non-null.

### ISSUE THREAD

**Issue by liuhedev** [marktext/marktext#3365]
### Description

An unexpected error occurred in the main process.

### Stack Trace

```
Error: Invalid state: all arguments must be non-null.
    at Object.register (/Applications/MarkText.app/Contents/Resources/app.asar/node_modules/@hfelix/electron-localshortcut/src/electron-localshortcut.js:167:11)
    at Object.registerKeyHandlers (/Applications/MarkText.app/Contents/Resources/app.asar/dist/electron/main.js:2:96468)
    at Object.addEditorMenu (/Applications/MarkText.app/Contents/Resources/app.asar/dist/electron/main.js:2:102654)
    at Kt.createWindow (/Applications/MarkText.app/Contents/Resources/app.asar/dist/electron/main.js:2:62142)
    at Object._createEditorWindow (/Applications/MarkText.app/Contents/Resources/app.asar/dist/electron/main.js:2:110155)
    at Object._openPathList (/Applications/MarkText.app/Contents/Resources/app.asar/dist/electron/main.js:2:111782)
    at Object._openFilesToOpen (/Applications/MarkText.app/Contents/Resources/app.asar/dist/electron/main.js:2:110486)
    at Object.ready (/Applications/MarkText.app/Contents/Resources/app.asar/dist/electron/main.js:2:108076)
    at App.<anonymous> (/Applications/MarkText.app/Contents/Resources/app.asar/dist/electron/main.js:2:109265)
    at App.emit (node:events:394:28)
```

### Version

MarkText: v0.17.0-rc.2
Operating system: Darwin x64 17.7.0 (darwin)

**Comment by Jocs** [comment]
Closing — this crash was reported against the legacy webpack-bundled build (the stack trace points into `dist/electron/renderer.js` / `dist/electron/main.js` / `webpack:/marktext/...`, which no longer exists).

The renderer + main process were rewritten on top of electron-vite in [PR #4001](https://github.com/marktext/marktext/pull/4001) (commit 85607dd2, shipped in 0.18.x). Many of the crash sites referenced in stacks like this were either rewritten, replaced, or now sit behind explicit guards. The general "Unexpected error" surface was also re-audited and given regression tests in [PR #4268](https://github.com/marktext/marktext/pull/4268).

**Please upgrade to the latest 0.18.x build. If you still hit a crash on a recent build, please reopen with the new MarkText version and the steps that triggered it — the new stack traces will point us to the actual current code.**
