### ISSUE TITLE
Unexpected error: Failed to execute 'setStart' on 'Range': There is no child at offset 4562.

### ISSUE THREAD

**Issue by Jakentop** [marktext/marktext#3378]
### Description

An unexpected error occurred in the renderer process.

![动画](https://user-images.githubusercontent.com/39620029/182331001-2b690191-eb0b-4632-8b4e-2ababf6f7375.gif)

### Stack Trace

```
Error: Failed to execute 'setStart' on 'Range': There is no child at offset 4562.
    at Object.select (file:///C:/Program%20Files/MarkText/resources/app.asar/dist/electron/renderer.js:2:160691)
    at Object.setCursorRange (file:///C:/Program%20Files/MarkText/resources/app.asar/dist/electron/renderer.js:2:162228)
    at Rs.setCursor (file:///C:/Program%20Files/MarkText/resources/app.asar/dist/electron/renderer.js:2:588628)
    at Rs.partialRender (file:///C:/Program%20Files/MarkText/resources/app.asar/dist/electron/renderer.js:2:589625)
    at Rs.e.backspaceHandler (file:///C:/Program%20Files/MarkText/resources/app.asar/dist/electron/renderer.js:2:500962)
    at HTMLDivElement.<anonymous> (file:///C:/Program%20Files/MarkText/resources/app.asar/dist/electron/renderer.js:2:606764)
```

### Version

MarkText: v0.17.1
Operating system: Windows_NT x64 10.0.17763 (win32)

**Comment by Jocs** [comment]
Closing this with the regression-guard e2e specs added in https://github.com/marktext/marktext/pull/4268.

The user-action recipe described here (and the same crash signature in ~25 other reports) does not reproduce on the current `develop` branch (0.18.9). The setCursorRange offset clamp at `src/muya/lib/selection/index.js:524-530` plus cumulative refactor fixes appear to have closed the underlying bug.

The recipes from these reports are now encoded as Playwright tests in `test/e2e/crash-range-offset.spec.ts` so a regression here will fail CI before it reaches another user.

**If you still hit this crash on a recent build, please reopen with the exact MarkText version and the markdown that triggered it.**
