### ISSUE TITLE
Why we need C++ build tools to build Marktext, and how can we set it up?

### ISSUE THREAD

**Issue by StephenChips** [marktext/marktext#3400]
### Question description

In the [Build Instruction](https://github.com/marktext/marktext/blob/develop/docs/dev/BUILD.md) it mentions that the C++ compiler and development tools is one of the prerequisite for building the application, but there is no furture instruction on how to set those tools up.

What kinds of toolchain do we needs: gcc/clang/CMake/Visual Studio/stdlibc++? Can I install it without installing Visual Studio, and use minGW-w64 as an alternative on Windows? I just don't want to install a HUGE C++ IDE just because the projects needs its compiler. If the anwser is YES, how can I set it up? Plus, should I set some environment variables for this project, so that it can find the toolchain?

I once installed VS on my computer (Windows 10) but I uninstalled it long time ago. I tried run `yarn install` directly without installing Visual Studio, but it complained it cannot find Visual Studio, and the installation process hung forever.

Following is the logs during `yarn install`:

```
yarn install v1.22.10
$ node .electron-vue/preinstall.js
[1/4] Resolving packages...
[2/4] Fetching packages...
warning file-icons@2.1.47: The engine "atom" appears to be invalid.
warning atom-fs@0.2.1: The engine "atom" appears to be invalid.
warning mapped-disposable@1.0.3: The engine "atom" appears to be invalid.
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info dmg-license@1.0.10: The platform "win32" is incompatible with this module.
info "dmg-license@1.0.10" is an optional dependency and failed compatibility check. Excluding it from installation.
info iconv-corefoundation@1.1.7: The platform "win32" is incompatible with this module.
info "iconv-corefoundation@1.1.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > eslint-config-standard@16.0.3" has incorrect peer dependency "eslint@^7.12.1".
warning " > eslint-config-standard@16.0.3" has incorrect peer dependency "eslint-plugin-promise@^4.2.1 || ^5.0.0".
[4/4] Building fresh packages...
[1/9] ⠐ electron
[2/9] ⠐ ced
[6/9] ⠐ native-keymap
[4/9] ⠈ fontmanager-redux
error C:\Users\23324\Documents\Codes\marktext\node_modules\native-keymap: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\Users\23324\Documents\Codes\marktext\node_modules\native-keymap
Output:
C:\Users\23324\Documents\Codes\marktext\node_modules\native-keymap>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.14.2 | win32 | x64
gyp info find Python using Python version 3.10.5 found at "C:\Users\23324\AppData\Local\Programs\Python\Python310\python.exe"
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:384:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:406:5)
gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\23324\Documents\Codes\marktext\node_modules\native-keymap
```

One more thing: What the heck is `gyp`? it seems this thing complained error and interrupts the installing process.

**Comment by Jocs** [comment]
MarkText includes native Node.js addons (spellcheck, keychain, etc.) that must be compiled for the target platform, which is why C++ build tools are required. With the current pnpm-based setup, `pnpm install` handles native addon compilation automatically via `scripts/postinstall.js`. Closing as answered.
