### ISSUE TITLE
Save as -> cancel -> exception

### ISSUE THREAD

**Issue by Pythonix** [marktext/marktext#347]
### Description

If you press Save as and then Cancel, there is an exception. See below.

### Steps to reproduce

1. save as
2. cancel

**Expected behavior:**
Do not save the file and catch undefined file path.

**Actual behavior:** 
```
Uncaught Exception:
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.extname (path.js:1471:5)
    at ve (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:1:102913)
    at EventEmitter.<anonymous> (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:1:114386)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)
    at WebContents.<anonymous> (/Applications/Mark Text.app/Contents/Resources/electron.asar/browser/api/web-contents.js:286:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
```

### Versions

- Mark Text: v0.12.20
- OS: Mac OS 10.11.6

**Comment by Jocs** [comment]
You are welcome to submit a PR to fix this issue.:smile:
