### ISSUE TITLE
Problem with building in WSL

### ISSUE THREAD

**Issue by MHYCWasTaken** [marktext/marktext#3521]
### Question description

Im working on WSL and im totally new for javascript, but i just wanna build a marktext for my self.

This is the enviroment im using :

```sh
$ node --version
v16.18.1

$ python3 --version
Python 3.8.2

$ yarn --version
1.22.19

$ g++ --version
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ sudo apt-get install libx11-dev libxkbfile-dev libsecret-1-dev libfontconfig-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libfontconfig1-dev' instead of 'libfontconfig-dev'
libfontconfig1-dev is already the newest version (2.13.1-2ubuntu3).
libxkbfile-dev is already the newest version (1:1.1.0-1).
libsecret-1-dev is already the newest version (0.20.4-0ubuntu1).
libx11-dev is already the newest version (2:1.6.9-2ubuntu1.2).
0 upgraded, 0 newly installed, 0 to remove and 298 not upgraded.

$ make --version
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

And i got this on running `yarn install --frozen-lockfile` : 

```sh
$ yarn install --frozen-lockfile
yarn install v1.22.19
$ node .electron-vue/preinstall.js
[1/4] Resolving packages...
[2/4] Fetching packages...
warning file-icons@2.1.47: The engine "atom" appears to be invalid.
warning atom-fs@0.2.1: The engine "atom" appears to be invalid.
warning mapped-disposable@1.0.3: The engine "atom" appears to be invalid.
[3/4] Linking dependencies...
warning " > eslint-config-standard@16.0.3" has incorrect peer dependency "eslint@^7.12.1".
warning " > eslint-config-standard@16.0.3" has incorrect peer dependency "eslint-plugin-promise@^4.2.1 || ^5.0.0".
[4/4] Building fresh packages...
[1/9] ⠄ electron
[2/9] ⠄ ced
[6/9] ⠄ native-keymap
[4/9] ⠄ fontmanager-redux
error /mnt/w/Projects/Software/TakeNotes/marktext-develop/node_modules/ced: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /mnt/w/Projects/Software/TakeNotes/marktext-develop/node_modules/ced
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@16.18.1 | linux | x64
gyp info find Python using Python version 3.8.2 found at "/usr/bin/python3"
gyp http GET https://nodejs.org/download/release/v16.18.1/node-v16.18.1-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack TypeError [ERR_INVALID_URL]: Invalid URL
gyp ERR! stack     at new NodeError (node:internal/errors:387:5)
gyp ERR! stack     at URL.onParseError (node:internal/url:565:9)
gyp ERR! stack     at new URL (node:internal/url:641:5)
gyp ERR! stack     at getProxyUri (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/agent.js:160:53)
gyp ERR! stack     at getAgent (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/agent.js:21:17)
gyp ERR! stack     at remoteFetch (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/remote.js:31:17)
gyp ERR! stack     at fetch (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/fetch.js:99:13)
gyp ERR! stack     at makeFetchHappen (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/index.js:10:10)
gyp ERR! stack     at download (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:354:21)
gyp ERR! stack     at go (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:150:27)
gyp ERR! System Linux 5.15.74.2-microsoft-standard-WSL2
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /mnt/w/Projects/Software/TakeNotes/marktext-develop/node_modules/ced
```

I think the question is on some url

(btw my network isn't stable here, this is the most common error, others are like "connection time out", "forbidden" etc.)

**Comment by Jocs** [comment]
Node.js v16 is below the required minimum (≥20.19.0), and the project no longer uses yarn. Please update to Node.js 20+ and use pnpm:
```bash
pnpm install
pnpm run dev
```
Closing as outdated environment.
