### ISSUE TITLE
Unexpected error: Failed to execute 'setStart' on 'Range': The offset 4294967292 is larger than the node's length (158).

### ISSUE THREAD

**Issue by wsscp** [marktext/marktext#3527]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
Error: Failed to execute 'setStart' on 'Range': The offset 4294967292 is larger than the node's length (158).
    at Object.classList [as select] (file:///opt/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/selection/index.js:339:28)
    at Object.setCursorRange (file:///opt/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/selection/index.js:485:79)
    at Rs.tokenCache [as setCursor] (file:///opt/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/index.js:198:5)
    at Rs.this [as render] (file:///opt/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/index.js:228:24)
    at Rs.preventDefault [as enterHandler] (file:///opt/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/enterCtrl.js:534:5)
    at HTMLDivElement.<anonymous> (file:///opt/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/eventHandler/keyboard.js:161:17)
```

### Version

MarkText: v0.17.1 (N/A)
Operating system: Linux x64 5.15.45-amd64-desktop (linux)

**Comment by Jocs** [comment]
This issue appears to be a duplicate of #2627.

The original issue: https://github.com/marktext/marktext/issues/2627

Adding the `🦞 resolved/duplicate` label. If you believe this is a distinct issue, please reopen with additional details explaining the difference.

*This comment was added automatically as part of a bulk deduplication pass.*
