### ISSUE TITLE
Unexpected error: Failed to execute 'setStart' on 'Range': There is no child at offset 909.

### ISSUE THREAD

**Issue by aimixsaka** [marktext/marktext#3542]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
Error: Failed to execute 'setStart' on 'Range': There is no child at offset 909.
    at Object.select (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/marktext/src/muya/lib/selection/index.js:346:11)
    at Object.setCursorRange (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/marktext/src/muya/lib/selection/index.js:491:10)
    at Rs.setCursor (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/index.js:207:15)
    at Rs.partialRender (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/index.js:272:12)
    at file:///usr/lib/marktext/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/inputCtrl.js:320:16
```

### Version

MarkText: v0.17.1 (aed36dbf)
Operating system: Linux x64 6.1.2-zen1-1-zen (linux)

**Comment by Jocs** [comment]
Closing this with the regression-guard e2e specs added in https://github.com/marktext/marktext/pull/4268.

The user-action recipe described here (and the same crash signature in ~25 other reports) does not reproduce on the current `develop` branch (0.18.9). The setCursorRange offset clamp at `src/muya/lib/selection/index.js:524-530` plus cumulative refactor fixes appear to have closed the underlying bug.

The recipes from these reports are now encoded as Playwright tests in `test/e2e/crash-range-offset.spec.ts` so a regression here will fail CI before it reaches another user.

**If you still hit this crash on a recent build, please reopen with the exact MarkText version and the markdown that triggered it.**
