### ISSUE TITLE
Unexpected error: Cannot destructure property 'text' of 'n' as it is null.

### ISSUE THREAD

**Issue by CarryWll** [marktext/marktext#3571]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
TypeError: Cannot destructure property 'text' of 'n' as it is null.
    at Rs.getCodeMirrorCursor (file:///C:/mySofts/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/utils/importMarkdown.js:454:19)
    at Ws.getCursor (file:///C:/mySofts/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/index.js:165:30)
    at Ws.dispatchChange (file:///C:/mySofts/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/index.js:109:25)
    at file:///C:/mySofts/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/eventHandler/keyboard.js:88:21
```

### Version

MarkText: v0.17.1 (N/A)
Operating system: Windows_NT x64 10.0.22000 (win32)

**Comment by Jocs** [comment]
Closing this with the regression-guard e2e specs added in https://github.com/marktext/marktext/pull/4268.

The crash in `paragraphCtrl.updateParagraph` no longer reproduces on the current `develop`. The upstream guard at `src/muya/lib/ui/quickInsert/index.js:160-164` (which short-circuits when `this.block` is null) plus `isAllowedTransformation` filtering prevent the null block from reaching the destructuring statement.

The original recipe (type `@` then pick Header 1) and adjacent paths (delete-paragraph-then-menu) are encoded as Playwright tests in `test/e2e/crash-update-paragraph.spec.ts`.

**If you still hit this crash on a recent build, please reopen with the exact MarkText version and the steps that triggered it.**
