### ISSUE TITLE
Unexpected error: Cannot destructure property 'text' of 'n' as it is null.

### ISSUE THREAD

**Issue by aimixsaka** [marktext/marktext#3607]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
TypeError: Cannot destructure property 'text' of 'n' as it is null.
    at Rs.getCodeMirrorCursor (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/marktext/src/muya/lib/utils/importMarkdown.js:454:19)
    at Ws.getCursor (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/marktext/src/muya/lib/index.js:165:30)
    at Ws.dispatchChange (file:///usr/lib/marktext/app.asar/dist/electron/webpack:/marktext/src/muya/lib/index.js:109:25)
    at file:///usr/lib/marktext/app.asar/dist/electron/webpack:/marktext/src/muya/lib/eventHandler/keyboard.js:88:21
```

### Version

MarkText: v0.17.1 (aed36dbf)
Operating system: Linux x64 6.2.8-zen1-1-zen (linux)

**Comment by Jocs** [comment]
This issue appears to be a duplicate of #3571.

The original issue: https://github.com/marktext/marktext/issues/3571

Adding the `🦞 resolved/duplicate` label. If you believe this is a distinct issue, please reopen with additional details explaining the difference.

*This comment was added automatically as part of a bulk deduplication pass.*
