### ISSUE TITLE
Unexpected error: Failed to execute 'setStart' on 'Range': There is no child at offset 9.

### ISSUE THREAD

**Issue by CuisoCat** [marktext/marktext#3636]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
Error: Failed to execute 'setStart' on 'Range': There is no child at offset 9.
    at Object.classList [as select] (file:///Applications/MarkText.app/Contents/Resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/selection/index.js:339:28)
    at Object.setCursorRange (file:///Applications/MarkText.app/Contents/Resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/selection/index.js:485:79)
    at Rs.key [as setCursor] (file:///Applications/MarkText.app/Contents/Resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/index.js:198:5)
    at Rs.isCollapse [as partialRender] (file:///Applications/MarkText.app/Contents/Resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/index.js:260:59)
    at Rs.contentState (file:///Applications/MarkText.app/Contents/Resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/inputCtrl.js:331:33)
    at HTMLDivElement.<anonymous> (file:///Applications/MarkText.app/Contents/Resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/eventHandler/keyboard.js:125:18)
```

### Version

MarkText: v0.17.1 (821244bf)
Operating system: Darwin arm64 22.4.0 (darwin)

**Comment by WilczynskiT** [comment]
Dear @CuisoCat ,

I hope this message finds you well. I wanted to inform you that the MarkText project has been abandoned. However, I have taken the initiative to reactivate the project under a new repository. You can find the reactivated project here: https://github.com/wilcz-com/wMarkText

I kindly request you to kindly transfer this issue to the new repository and continue the discussion and development efforts there. Your continued support and contributions would be greatly appreciated.

Thank you for your understanding and cooperation.

Best regards,
WilczynskiT

**Comment by Jocs** [comment]
Closing this with the regression-guard e2e specs added in https://github.com/marktext/marktext/pull/4268.

The user-action recipe described here (and the same crash signature in ~25 other reports) does not reproduce on the current `develop` branch (0.18.9). The setCursorRange offset clamp at `src/muya/lib/selection/index.js:524-530` plus cumulative refactor fixes appear to have closed the underlying bug.

The recipes from these reports are now encoded as Playwright tests in `test/e2e/crash-range-offset.spec.ts` so a regression here will fail CI before it reaches another user.

**If you still hit this crash on a recent build, please reopen with the exact MarkText version and the markdown that triggered it.**
