### ISSUE TITLE
Unexpected error: Cannot read properties of null (reading 'id')

### ISSUE THREAD

**Issue by singlecharacterx** [marktext/marktext#3660]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
TypeError: Cannot read properties of null (reading 'id')
    at Rs.isComposed [as arrowHandler] (file:///D:/marktext/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/arrowCtrl.js:87:7)
    at HTMLDivElement.<anonymous> (file:///D:/marktext/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/eventHandler/keyboard.js:174:21)
```

### Version

MarkText: v0.17.1 (00f5061f)
Operating system: Windows_NT x64 10.0.19045 (win32)

**Comment by Jocs** [comment]
how to reproduce it?
