### ISSUE TITLE
Unexpected error: Cannot destructure property 'text' of 'o' as it is null.

### ISSUE THREAD

**Issue by Joe978** [marktext/marktext#3667]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
TypeError: Cannot destructure property 'text' of 'o' as it is null.
    at Rs.filter [as updateParagraph] (file:///D:/marktext/marktext-1.0beta-win64/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/paragraphCtrl.js:447:7)
    at oc.selectItem (file:///D:/marktext/marktext-1.0beta-win64/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/ui/quickInsert/index.js:119:23)
    at Object.click (file:///D:/marktext/marktext-1.0beta-win64/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/ui/quickInsert/index.js:56:34)
    at invokeHandler (D:\marktext\marktext-1.0beta-win64\resources\app.asar\node_modules\snabbdom\build\snabbdom.cjs.js:804:17)
    at handleEvent (D:\marktext\marktext-1.0beta-win64\resources\app.asar\node_modules\snabbdom\build\snabbdom.cjs.js:818:9)
    at HTMLDivElement.handler (D:\marktext\marktext-1.0beta-win64\resources\app.asar\node_modules\snabbdom\build\snabbdom.cjs.js:823:9)
```

### Version

MarkText: v0.17.1 (00f5061f)
Operating system: Windows_NT x64 10.0.22621 (win32)

**Comment by Jocs** [comment]
Closing this with the regression-guard e2e specs added in https://github.com/marktext/marktext/pull/4268.

The crash in `paragraphCtrl.updateParagraph` no longer reproduces on the current `develop`. The upstream guard at `src/muya/lib/ui/quickInsert/index.js:160-164` (which short-circuits when `this.block` is null) plus `isAllowedTransformation` filtering prevent the null block from reaching the destructuring statement.

The original recipe (type `@` then pick Header 1) and adjacent paths (delete-paragraph-then-menu) are encoded as Playwright tests in `test/e2e/crash-update-paragraph.spec.ts`.

**If you still hit this crash on a recent build, please reopen with the exact MarkText version and the steps that triggered it.**
