### ISSUE TITLE
Unexpected error: Cannot destructure property 'text' of 'n' as it is null.

### ISSUE THREAD

**Issue by lfsun666** [marktext/marktext#3687]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
TypeError: Cannot destructure property 'text' of 'n' as it is null.
    at Rs.e.getCodeMirrorCursor (file:///E:/Downloads/marktext-1.0beta-win64/resources/app.asar/dist/electron/renderer.js:2:582716)
    at Ws.getCursor (file:///E:/Downloads/marktext-1.0beta-win64/resources/app.asar/dist/electron/renderer.js:2:612712)
    at Ws.<anonymous> (file:///E:/Downloads/marktext-1.0beta-win64/resources/app.asar/dist/electron/renderer.js:2:596912)
    at file:///E:/Downloads/marktext-1.0beta-win64/resources/app.asar/dist/electron/renderer.js:2:606070
```

### Version

MarkText: v0.17.1 (00f5061f)
Operating system: Windows_NT x64 10.0.18363 (win32)

**Comment by Jocs** [comment]
This issue appears to be a duplicate of #3571.

The original issue: https://github.com/marktext/marktext/issues/3571

Adding the `🦞 resolved/duplicate` label. If you believe this is a distinct issue, please reopen with additional details explaining the difference.

*This comment was added automatically as part of a bulk deduplication pass.*
