### ISSUE TITLE
Unexpected error: Cannot read properties of null (reading 'functionType')

### ISSUE THREAD

**Issue by cnxjk** [marktext/marktext#3698]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
TypeError: Cannot read properties of null (reading 'functionType')
    at Rs.paragraph [as updateCodeLanguage] (file:///Applications/MarkText.app/Contents/Resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/codeBlockCtrl.js:51:26)
    at Rs.event [as selectLanguage] (file:///Applications/MarkText.app/Contents/Resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/codeBlockCtrl.js:34:20)
    at activeItem (file:///Applications/MarkText.app/Contents/Resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/eventHandler/keyboard.js:203:35)
    at lc.event [as selectItem] (file:///Applications/MarkText.app/Contents/Resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/ui/baseScrollFloat/index.js:79:10)
    at HTMLDivElement.<anonymous> (file:///Applications/MarkText.app/Contents/Resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/ui/baseScrollFloat/index.js:33:21)
```

### Version

MarkText: v0.17.1 (821244bf)
Operating system: Darwin arm64 23.0.0 (darwin)

**Comment by Jocs** [comment]
This issue appears to be a duplicate of #3672.

The original issue: https://github.com/marktext/marktext/issues/3672

Adding the `🦞 resolved/duplicate` label. If you believe this is a distinct issue, please reopen with additional details explaining the difference.

*This comment was added automatically as part of a bulk deduplication pass.*
