### ISSUE TITLE
Unexpected error: Cannot read properties of null (reading 'type')

### ISSUE THREAD

**Issue by caoyongren** [marktext/marktext#3723]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
TypeError: Cannot read properties of null (reading 'type')
    at file:///C:/cao/marktext-1.0beta-win64/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/paragraphCtrl.js:23:36
    at Array.filter (<anonymous>)
    at Rs.getTOC [as selectionChange] (file:///C:/cao/marktext-1.0beta-win64/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/paragraphCtrl.js:21:23)
    at Ws.<anonymous> (file:///C:/cao/marktext-1.0beta-win64/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/index.js:111:22)
    at file:///C:/cao/marktext-1.0beta-win64/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/eventHandler/keyboard.js:72:7
```

### Version

MarkText: v0.17.1 (00f5061f)
Operating system: Windows_NT x64 10.0.19044 (win32)

**Comment by shantanu-wdev** [comment]
Please provide the steps to reproduce.

**Comment by Jocs** [comment]
This issue appears to be a duplicate of #3679.

The original issue: https://github.com/marktext/marktext/issues/3679

Adding the `🦞 resolved/duplicate` label. If you believe this is a distinct issue, please reopen with additional details explaining the difference.

*This comment was added automatically as part of a bulk deduplication pass.*
