### ISSUE TITLE
Unexpected error: Failed to execute 'setStart' on 'Range': There is no child at offset 1766.

### ISSUE THREAD

**Issue by ProudRabbit** [marktext/marktext#3737]
当删除代码块时没有使用代码块左边的删除按钮，而是直接使用键盘backspace删除文字时，报错。

### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
Error: Failed to execute 'setStart' on 'Range': There is no child at offset 1766.
    at Object.classList [as select] (file:///D:/Program_Files/marktext/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/selection/index.js:339:28)
    at Object.setCursorRange (file:///D:/Program_Files/marktext/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/selection/index.js:485:79)
    at Rs.key [as setCursor] (file:///D:/Program_Files/marktext/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/index.js:198:5)
    at Rs.key [as partialRender] (file:///D:/Program_Files/marktext/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/index.js:260:59)
    at Rs.e.backspaceHandler (file:///D:/Program_Files/marktext/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/backspaceCtrl.js:552:16)
    at HTMLDivElement.<anonymous> (file:///D:/Program_Files/marktext/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/eventHandler/keyboard.js:152:27)
```

### Version

MarkText: v0.17.1 (00f5061f)
Operating system: Windows_NT x64 10.0.19045 (win32)

**Comment by Jocs** [comment]
Closing this with the regression-guard e2e specs added in https://github.com/marktext/marktext/pull/4268.

The user-action recipe described here (and the same crash signature in ~25 other reports) does not reproduce on the current `develop` branch (0.18.9). The setCursorRange offset clamp at `src/muya/lib/selection/index.js:524-530` plus cumulative refactor fixes appear to have closed the underlying bug.

The recipes from these reports are now encoded as Playwright tests in `test/e2e/crash-range-offset.spec.ts` so a regression here will fail CI before it reaches another user.

**If you still hit this crash on a recent build, please reopen with the exact MarkText version and the markdown that triggered it.**
