### ISSUE TITLE
Using the arrow key ↑ in a first-level heading causes an error

### ISSUE THREAD

**Issue by KirsminX** [marktext/marktext#3762]
### Description

Using the arrow key ↑ in a first-level heading causes an error

### Stack Trace

```
TypeError: Cannot read properties of null (reading 'id')
    at Rs.isComposed [as arrowHandler] (file:///C:/DiyFile/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/arrowCtrl.js:87:7)
    at HTMLDivElement.<anonymous> (file:///C:/DiyFile/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/eventHandler/keyboard.js:174:21)
```

### Version

MarkText: v0.17.1 (00f5061f)
Operating system: Windows_NT x64 10.0.22631 (win32)

**Comment by Jocs** [comment]
Thanks for the detailed stack trace! This crash came from the legacy editor engine (`src/muya/lib/contentState/arrowCtrl.js`), which dereferenced `paragraph.id` on a null node when the up arrow moved the caret out of a top heading. MarkText's editor has since been rewritten on the new `@muyajs/core` engine, where the arrow-key handler lives on the content block itself and explicitly handles the "no previous block" boundary (it simply does nothing instead of throwing), so pressing ↑ in a first-level heading no longer errors. I'm closing this as resolved by the engine migration — if you can still reproduce it on the latest build, please reopen with steps and we'll take another look.
