### ISSUE TITLE
Unexpected error: Cannot read properties of null (reading 'type')

### ISSUE THREAD

**Issue by hello-jiangxiaoyu** [marktext/marktext#3775]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
TypeError: Cannot read properties of null (reading 'type')
    at file:///D:/Sorftware/tools/marktext/marktext-x64-win/resources/app.asar/dist/electron/renderer.js:2:537792
    at Array.filter (<anonymous>)
    at Rs.e.selectionChange (file:///D:/Sorftware/tools/marktext/marktext-x64-win/resources/app.asar/dist/electron/renderer.js:2:537767)
    at Ws.<anonymous> (file:///D:/Sorftware/tools/marktext/marktext-x64-win/resources/app.asar/dist/electron/renderer.js:2:597101)
    at file:///D:/Sorftware/tools/marktext/marktext-x64-win/resources/app.asar/dist/electron/renderer.js:2:605961
```

### Version

MarkText: v1.0.0 (749076e6)
Operating system: Windows_NT x64 10.0.22631 (win32)

**Comment by Jocs** [comment]
Closing — this crash was reported against the legacy webpack-bundled build (the stack trace points into `dist/electron/renderer.js` / `dist/electron/main.js` / `webpack:/marktext/...`, which no longer exists).

The renderer + main process were rewritten on top of electron-vite in [PR #4001](https://github.com/marktext/marktext/pull/4001) (commit 85607dd2, shipped in 0.18.x). Many of the crash sites referenced in stacks like this were either rewritten, replaced, or now sit behind explicit guards. The general "Unexpected error" surface was also re-audited and given regression tests in [PR #4268](https://github.com/marktext/marktext/pull/4268).

**Please upgrade to the latest 0.18.x build. If you still hit a crash on a recent build, please reopen with the new MarkText version and the steps that triggered it — the new stack traces will point us to the actual current code.**
