### ISSUE TITLE
Unexpected error: Failed to execute 'setStart' on 'Range': The offset 4294967292 is larger than the node's length (14).

### ISSUE THREAD

**Issue by renanrod4** [marktext/marktext#3782]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
Error: Failed to execute 'setStart' on 'Range': The offset 4294967292 is larger than the node's length (14).
    at Object.select (file:///tmp/.mount_markteHGQRmn/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/selection/index.js:346:11)
    at Object.setCursorRange (file:///tmp/.mount_markteHGQRmn/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/selection/index.js:491:10)
    at $a.setCursor (file:///tmp/.mount_markteHGQRmn/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/index.js:207:15)
    at $a.render (file:///tmp/.mount_markteHGQRmn/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/index.js:237:12)
    at $a.enterHandler (file:///tmp/.mount_markteHGQRmn/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/enterCtrl.js:550:26)
    at HTMLDivElement.<anonymous> (file:///tmp/.mount_markteHGQRmn/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/eventHandler/keyboard.js:175:26)
```

### Version

MarkText: v0.17.4 (2b9803cc)
Operating system: Linux x64 6.5.0-26-generic (linux)

**Comment by Jocs** [comment]
This issue appears to be a duplicate of #2627.

The original issue: https://github.com/marktext/marktext/issues/2627

Adding the `🦞 resolved/duplicate` label. If you believe this is a distinct issue, please reopen with additional details explaining the difference.

*This comment was added automatically as part of a bulk deduplication pass.*
