### ISSUE TITLE
Unexpected error: Cannot read properties of undefined (reading 'children')

### ISSUE THREAD

**Issue by ISOEhy** [marktext/marktext#3792]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
TypeError: Cannot read properties of undefined (reading 'children')
    at ms.indent [as normalizeCodeBlock] (file:///Applications/MarkText.app/Contents/Resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/utils/exportMarkdown.js:256:10)
    at ms.this [as translateBlocks2Markdown] (file:///Applications/MarkText.app/Contents/Resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/utils/exportMarkdown.js:144:49)
    at ms.subtree [as generate] (file:///Applications/MarkText.app/Contents/Resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/utils/exportMarkdown.js:23:7)
    at Ws.getMarkdown (file:///Applications/MarkText.app/Contents/Resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/index.js:72:39)
    at Ws.clearTimeout (file:///Applications/MarkText.app/Contents/Resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/index.js:19:13)
    at file:///Applications/MarkText.app/Contents/Resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/eventHandler/keyboard.js:83:18
```

### Version

MarkText: v0.17.1 (821244bf)
Operating system: Darwin x64 23.4.0 (darwin)

**Comment by Jocs** [comment]
Closing — this crash was reported against the legacy webpack-bundled build (the stack trace points into `dist/electron/renderer.js` / `dist/electron/main.js` / `webpack:/marktext/...`, which no longer exists).

The renderer + main process were rewritten on top of electron-vite in [PR #4001](https://github.com/marktext/marktext/pull/4001) (commit 85607dd2, shipped in 0.18.x). Many of the crash sites referenced in stacks like this were either rewritten, replaced, or now sit behind explicit guards. The general "Unexpected error" surface was also re-audited and given regression tests in [PR #4268](https://github.com/marktext/marktext/pull/4268).

**Please upgrade to the latest 0.18.x build. If you still hit a crash on a recent build, please reopen with the new MarkText version and the steps that triggered it — the new stack traces will point us to the actual current code.**
