### ISSUE TITLE
Unexpected error: Failed to execute 'setStart' on 'Range': There is no child at offset 12.

### ISSUE THREAD

**Issue by jiang-yuntao** [marktext/marktext#3793]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
Error: Failed to execute 'setStart' on 'Range': There is no child at offset 12.
    at Object.classList [as select] (file:///opt/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/selection/index.js:339:28)
    at Object.setCursorRange (file:///opt/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/selection/index.js:485:79)
    at Rs.key [as setCursor] (file:///opt/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/index.js:198:5)
    at Rs.cursor [as partialRender] (file:///opt/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/index.js:260:59)
    at Rs.e.clickHandler (file:///opt/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/clickCtrl.js:176:24)
    at HTMLDivElement.<anonymous> (file:///opt/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/eventHandler/clickEvent.js:224:52)
```

### Version

MarkText: v0.17.1 (N/A)
Operating system: Linux x64 6.1.0-20-amd64 (linux)

**Comment by Jocs** [comment]
Closing this with the regression-guard e2e specs added in https://github.com/marktext/marktext/pull/4268.

The user-action recipe described here (and the same crash signature in ~25 other reports) does not reproduce on the current `develop` branch (0.18.9). The setCursorRange offset clamp at `src/muya/lib/selection/index.js:524-530` plus cumulative refactor fixes appear to have closed the underlying bug.

The recipes from these reports are now encoded as Playwright tests in `test/e2e/crash-range-offset.spec.ts` so a regression here will fail CI before it reaches another user.

**If you still hit this crash on a recent build, please reopen with the exact MarkText version and the markdown that triggered it.**
