### ISSUE TITLE
Unexpected error: EMFILE: too many open files, open 'C:\Users\FangYong\AppData\Roaming\marktext\preferences.json'

### ISSUE THREAD

**Issue by zhaoweilong007** [marktext/marktext#3817]
### Description

An unexpected error occurred in the main process.

### Stack Trace

```
Error: EMFILE: too many open files, open 'C:\Users\FangYong\AppData\Roaming\marktext\preferences.json'
    at Object.openSync (node:fs:582:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1800)
    at Object.readFileSync (node:fs:450:35)
    at Object.e.readFileSync (node:electron/js2c/asar_bundle:5:9148)
    at ElectronStore.get store [as store] (C:\Users\FangYong\AppData\Local\Programs\MarkText\resources\app.asar\node_modules\conf\dist\source\index.js:276:29)
    at ElectronStore._get (C:\Users\FangYong\AppData\Local\Programs\MarkText\resources\app.asar\node_modules\conf\dist\source\index.js:465:33)
    at ElectronStore.get (C:\Users\FangYong\AppData\Local\Programs\MarkText\resources\app.asar\node_modules\conf\dist\source\index.js:155:25)
    at sn.getItem (C:\Users\FangYong\AppData\Local\Programs\MarkText\resources\app.asar\dist\electron\main.js:2:280264)
    at sn.getPreferredEol (C:\Users\FangYong\AppData\Local\Programs\MarkText\resources\app.asar\dist\electron\main.js:2:280450)
    at Xt.openTabs (C:\Users\FangYong\AppData\Local\Programs\MarkText\resources\app.asar\dist\electron\main.js:2:256349)
```

### Version

MarkText: v0.17.1
Operating system: Windows_NT x64 10.0.22631 (win32)

**Comment by Jocs** [comment]
This issue appears to be a duplicate of #2906.

The original issue: https://github.com/marktext/marktext/issues/2906

Adding the `🦞 resolved/duplicate` label. If you believe this is a distinct issue, please reopen with additional details explaining the difference.

*This comment was added automatically as part of a bulk deduplication pass.*
