### ISSUE TITLE
Unexpected error: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by wzwyz** [marktext/marktext#3820]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
TypeError: Cannot read properties of undefined (reading 'length')
    at ms.normalizeTable (file:///D:/Software/marktext-1.0beta-win64/resources/app.asar/dist/electron/renderer.js:2:463342)
    at ms.translateBlocks2Markdown (file:///D:/Software/marktext-1.0beta-win64/resources/app.asar/dist/electron/renderer.js:2:459831)
    at ms.generate (file:///D:/Software/marktext-1.0beta-win64/resources/app.asar/dist/electron/renderer.js:2:459274)
    at Ws.getMarkdown (file:///D:/Software/marktext-1.0beta-win64/resources/app.asar/dist/electron/renderer.js:2:612277)
    at Ws.<anonymous> (file:///D:/Software/marktext-1.0beta-win64/resources/app.asar/dist/electron/renderer.js:2:596868)
    at file:///D:/Software/marktext-1.0beta-win64/resources/app.asar/dist/electron/renderer.js:2:606070
```

### Version

MarkText: v0.17.1 (00f5061f)
Operating system: Windows_NT x64 10.0.22635 (win32)

**Comment by Jocs** [comment]
This issue appears to be a duplicate of #3705.

The original issue: https://github.com/marktext/marktext/issues/3705

Adding the `🦞 resolved/duplicate` label. If you believe this is a distinct issue, please reopen with additional details explaining the difference.

*This comment was added automatically as part of a bulk deduplication pass.*
