### ISSUE TITLE
Unexpected error: Cannot read properties of null (reading 'text')

### ISSUE THREAD

**Issue by tianxiaogua** [marktext/marktext#3826]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
TypeError: Cannot read properties of null (reading 'text')
    at Rs.this [as checkNeedRender] (file:///D:/app/marktext-1.0beta-win64/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/updateCtrl.js:27:47)
    at Rs.e.clickHandler (file:///D:/app/marktext-1.0beta-win64/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/clickCtrl.js:167:24)
    at HTMLDivElement.<anonymous> (file:///D:/app/marktext-1.0beta-win64/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/eventHandler/clickEvent.js:224:52)
```

### Version

MarkText: v0.17.1 (00f5061f)
Operating system: Windows_NT x64 10.0.22631 (win32)

**Comment by Jocs** [comment]
This issue appears to be a duplicate of #3674.

The original issue: https://github.com/marktext/marktext/issues/3674

Adding the `🦞 resolved/duplicate` label. If you believe this is a distinct issue, please reopen with additional details explaining the difference.

*This comment was added automatically as part of a bulk deduplication pass.*
