### ISSUE TITLE
Unexpected error: Cannot destructure property 'pathname' of 'e.tabs[o]' as it is undefined.

### ISSUE THREAD

**Issue by Rise1024** [marktext/marktext#3866]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
TypeError: Cannot destructure property 'pathname' of 'e.tabs[o]' as it is undefined.
    at forEach (file:///Applications/MarkText.app/Contents/Resources/app.asar/dist/electron/webpack:/marktext/src/renderer/store/editor.js:256:15)
    at Array.forEach (<anonymous>)
    at Store.CLOSE_TABS (file:///Applications/MarkText.app/Contents/Resources/app.asar/dist/electron/webpack:/marktext/src/renderer/store/editor.js:254:15)
    at wrappedMutationHandler (/Applications/MarkText.app/Contents/Resources/app.asar/node_modules/vuex/dist/vuex.common.js:846:13)
    at commitIterator (/Applications/MarkText.app/Contents/Resources/app.asar/node_modules/vuex/dist/vuex.common.js:468:7)
    at Array.forEach (<anonymous>)
    at /Applications/MarkText.app/Contents/Resources/app.asar/node_modules/vuex/dist/vuex.common.js:467:11
    at Store._withCommit (/Applications/MarkText.app/Contents/Resources/app.asar/node_modules/vuex/dist/vuex.common.js:626:3)
    at Store.commit (/Applications/MarkText.app/Contents/Resources/app.asar/node_modules/vuex/dist/vuex.common.js:466:8)
    at boundCommit (/Applications/MarkText.app/Contents/Resources/app.asar/node_modules/vuex/dist/vuex.common.js:411:19)
```

### Version

MarkText: v0.17.1 (N/A)
Operating system: Darwin arm64 23.3.0 (darwin)

**Comment by Jocs** [comment]
This issue appears to be a duplicate of #3551.

The original issue: https://github.com/marktext/marktext/issues/3551

Adding the `🦞 resolved/duplicate` label. If you believe this is a distinct issue, please reopen with additional details explaining the difference.

*This comment was added automatically as part of a bulk deduplication pass.*
