### ISSUE TITLE
Unexpected error: Cannot destructure property 'text' of 'n' as it is null.

### ISSUE THREAD

**Issue by Mrx1992** [marktext/marktext#3872]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
TypeError: Cannot destructure property 'text' of 'n' as it is null.
    at Rs.generate [as getCodeMirrorCursor] (file:///opt/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/utils/importMarkdown.js:449:16)
    at Ws.options [as getCursor] (file:///opt/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/index.js:152:43)
    at Ws.clearTimeout (file:///opt/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/index.js:22:7)
    at file:///opt/MarkText/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/eventHandler/keyboard.js:83:18
```

### Version

MarkText: v0.17.1 (N/A)
Operating system: Linux x64 6.1.0-25-amd64 (linux)

**Comment by Jocs** [comment]
This issue appears to be a duplicate of #3571.

The original issue: https://github.com/marktext/marktext/issues/3571

Adding the `🦞 resolved/duplicate` label. If you believe this is a distinct issue, please reopen with additional details explaining the difference.

*This comment was added automatically as part of a bulk deduplication pass.*
