### ISSUE TITLE
Unexpected error: Cannot read properties of null (reading 'text')

### ISSUE THREAD

**Issue by fuyao-lhw** [marktext/marktext#3887]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
TypeError: Cannot read properties of null (reading 'text')
    at Rs.e.checkNeedRender (file:///E:/soft_download/MarkText/marktext-1.0beta-win64/resources/app.asar/dist/electron/renderer.js:2:485153)
    at Rs.e.clickHandler (file:///E:/soft_download/MarkText/marktext-1.0beta-win64/resources/app.asar/dist/electron/renderer.js:2:561922)
    at HTMLDivElement.<anonymous> (file:///E:/soft_download/MarkText/marktext-1.0beta-win64/resources/app.asar/dist/electron/renderer.js:2:604728)
```

### Version

MarkText: v0.17.1 (00f5061f)
Operating system: Windows_NT x64 10.0.22631 (win32)

**Comment by Ar-Kareem** [comment]
Can you describe how to replicate this issue?
Did you open a specific file? Is the application working when you open other or new files?

**Comment by Jocs** [comment]
This issue appears to be a duplicate of #3674.

The original issue: https://github.com/marktext/marktext/issues/3674

Adding the `🦞 resolved/duplicate` label. If you believe this is a distinct issue, please reopen with additional details explaining the difference.

*This comment was added automatically as part of a bulk deduplication pass.*
