### ISSUE TITLE
Unexpected error: Cannot destructure property 'text' of 'o' as it is null.

### ISSUE THREAD

**Issue by Vessels-W** [marktext/marktext#3899]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
TypeError: Cannot destructure property 'text' of 'o' as it is null.
    at Rs.filter [as updateParagraph] (file:///C:/Users/23011/AppData/Local/Temp/BNZ.67701d2dfcd2f13/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/contentState/paragraphCtrl.js:447:7)
    at oc.event [as selectItem] (file:///C:/Users/23011/AppData/Local/Temp/BNZ.67701d2dfcd2f13/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/ui/quickInsert/index.js:119:23)
    at HTMLDivElement.<anonymous> (file:///C:/Users/23011/AppData/Local/Temp/BNZ.67701d2dfcd2f13/resources/app.asar/dist/electron/webpack:/marktext/src/muya/lib/ui/baseScrollFloat/index.js:33:21)
```

### Version

MarkText: v0.17.1 (00f5061f)
Operating system: Windows_NT x64 10.0.22631 (win32)

**Comment by Jocs** [comment]
This issue appears to be a duplicate of #3663.

The original issue: https://github.com/marktext/marktext/issues/3663

Adding the `🦞 resolved/duplicate` label. If you believe this is a distinct issue, please reopen with additional details explaining the difference.

*This comment was added automatically as part of a bulk deduplication pass.*
