### ISSUE TITLE
Unexpected error: Cannot read property 'width' of undefined

### ISSUE THREAD

**Issue by Yihen** [marktext/marktext#632]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
TypeError: Cannot read property 'width' of undefined
    at file:///Applications/Mark%20Text.app/Contents/Resources/app.asar/dist/electron/renderer.js:13:3191664
    at Array.map (<anonymous>)
    at file:///Applications/Mark%20Text.app/Contents/Resources/app.asar/dist/electron/renderer.js:13:3191616
    at Array.forEach (<anonymous>)
    at A.value (file:///Applications/Mark%20Text.app/Contents/Resources/app.asar/dist/electron/renderer.js:13:3191580)
    at A.value (file:///Applications/Mark%20Text.app/Contents/Resources/app.asar/dist/electron/renderer.js:13:3187673)
    at A.value (file:///Applications/Mark%20Text.app/Contents/Resources/app.asar/dist/electron/renderer.js:13:3186940)
    at A.value (file:///Applications/Mark%20Text.app/Contents/Resources/app.asar/dist/electron/renderer.js:13:3251915)
    at A.value (file:///Applications/Mark%20Text.app/Contents/Resources/app.asar/dist/electron/renderer.js:13:3251683)
    at file:///Applications/Mark%20Text.app/Contents/Resources/app.asar/dist/electron/renderer.js:13:3245546
```

### Version

Mark Text: 0.13.65 (4d0f08e)
Operating system: darwin

**Comment by Jocs** [comment]
how to reproduce this issue

**Comment by fxha** [comment]
@Yihen Can you please use the latest master and/or give us instruction how to reproduce the issue.  I'm closing the issue because we cannot reproduce the error.
