### ISSUE TITLE
Unexpected error: Cannot read property 'nodeType' of null

### ISSUE THREAD

**Issue by xianmin** [marktext/marktext#692]
### Description

An unexpected error occurred in the renderer process.

1. Write something, then select.
2. If my mouse move to **title bar** , and delete, an error occur.

![deepin-screen-recorder_electron_20190217073921](https://user-images.githubusercontent.com/2177570/52906483-bf1f8b00-3287-11e9-8b81-3c9a4bbf1eb7.gif)

### Stack Trace

```
TypeError: Cannot read property 'nodeType' of null
    at getNodeAndOffset (webpack-internal:///./src/muya/lib/selection/index.js:327:16)
    at Selection.setCursorRange (webpack-internal:///./src/muya/lib/selection/index.js:348:52)
    at ContentState.setCursor (webpack-internal:///./src/muya/lib/contentState/index.js:138:56)
    at ContentState.partialRender (webpack-internal:///./src/muya/lib/contentState/index.js:177:10)
    at ContentState.inputHandler (webpack-internal:///./src/muya/lib/contentState/inputCtrl.js:105:51)
    at HTMLDivElement.inputHandler (webpack-internal:///./src/muya/lib/eventHandler/keyboard.js:124:22)
```

### Version

Mark Text: v0.13.65 (master - a55fc94)
Operating system: linux

**Comment by xianmin** [comment]
Relate issue: https://github.com/marktext/marktext/issues/578

**Comment by Jocs** [comment]
@xianmin I can not reproduce this issue on master branch, can you reproduce it now?

**Comment by xianmin** [comment]
@Jocs Yes. In the test above, my text is:

```
## test

test
```

I guess it relate with heading or selection or lost my mouse focus. Here is another test:

![deepin-screen-recorder_electron_20190303233203](https://user-images.githubusercontent.com/2177570/53697588-a5488100-3e0d-11e9-80e7-611d7437ef21.gif)

If my mouse move to the `heading` , the `heading` will show **Hashtag (#)** , then I delete, it's run well.
