### ISSUE TITLE
Can't parse simple table with cursor on last character

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#81]
### Description

If you parse the following table with cursor position on the last character, the editor throws exceptions.

```
| a | b |
| --- | --- |
| a | b |
| a | b |<--- cursor position
```

### Steps to reproduce

![mt_table_bug_cursor](https://user-images.githubusercontent.com/22716132/37897276-1f4d8346-30e6-11e8-89d5-2e95375592eb.png)

**Expected behavior:**

| a | b |
| --- | --- |
| a | b |
| a | b |

**Actual behavior:**

```
TypeError: Cannot read property 'width' of undefined
    at marktext/dist/electron/renderer.js:1:306269
    at Array.map (<anonymous>)
    at marktext/dist/electron/renderer.js:1:306222
    at Array.forEach (<anonymous>)
    at e.value (marktext/dist/electron/renderer.js:1:306186)
    at e.value (marktext/dist/electron/renderer.js:1:304466)
    at e.value (marktext/dist/electron/renderer.js:1:303957)
    at e.value (marktext/dist/electron/renderer.js:24:102073)
    at e.value (marktext/dist/electron/renderer.js:24:97041)
    at HTMLDivElement.o (marktext/dist/electron/renderer.js:24:101256)
```

[renderer.js:1:306269 = src/editor/parser/exportMarkdown.js#L142](https://github.com/marktext/marktext/blob/b73abe33e1cf3c0d2f9f9656b20e82a68c696b2c/src/editor/utils/exportMarkdown.js#L141)

![mt_table_bug](https://user-images.githubusercontent.com/22716132/37897221-0062badc-30e6-11e8-8d8d-045dc6042bee.png)

### Versions

- Mark Text: 0.8.8 and 0.8.12
- OS: linux

**Comment by Jocs** [comment]
maybe we need to reset the cursor to the position before the last `|` when cursor is after the last `|`.

**Comment by Jocs** [comment]
@fxha fixed.
